import UpperPrunedGraphData
import UpperGraphSwitchingFastCheck

/- Generated by research/generate_pruned_graph_cover.py.
202 graph representatives reach 31 of the unchanged 131 contact representatives. -/

namespace LittlewoodCylinders.Upper.GraphCover

set_option maxRecDepth 65536
set_option maxHeartbeats 0

def contactReps131 : Array ℕ := #[
  0, 142936511610880, 8552960, 4956392259648, 1342455828, 4432406249698,
  147892903870528, 142936520163840, 142936784241680, 160666138214912, 696322132480, 17729626604162,
  2189591170, 142937854066708, 4433480253666, 147892908065856, 17729897103384, 4956400812608,
  811601050, 4957734715476, 160666138215042, 811634200, 2458026642, 17661451999744,
  8867002102272, 35745041646080, 160668319252992, 147895084908738, 160666408714264, 178259002787840,
  142936782176922, 17729897136664, 142938701202050, 147892912423488, 213880789926018, 169530950726144,
  2992672280, 53473561149440, 696590568082, 662499021348, 187544176177282, 143074500709888,
  178816811696640, 160666679283200, 35744205111320, 142937323211930, 160666687769600, 178817340049920,
  178679904734338, 594895078050, 160668589752344, 17730436107792, 142936788615830, 17729897136794,
  53335580216450, 17731243740168, 142937864700440, 160666408747544, 160668319253122, 35743122621082,
  160666679250050, 4958581850818, 213880789959298, 178258734350482, 142938969637522, 662499021478,
  35743663656090, 53473565344768, 4399670152772, 277403058838, 71177523862, 79597665132544,
  662501118508, 160600140324352, 834104625810, 178749165703680, 178817348569600, 160668860321280,
  35743663689240, 196408990270082, 17730434009754, 142971685193910, 35743665916562, 160599607775874,
  143495671220882, 160666947718672, 143632573825682, 178713731973668, 160666408747674, 17730438204952,
  35881096874642, 53472749191704, 160529510338072, 178156191500340, 147895093461698, 484898019848,
  160667491254300, 178852245422116, 178886068050432, 53473831682072, 169496603665570, 178680716738588,
  664688562850, 26947437472922, 143529494102710, 240269070082690, 88538650674818, 143633110698642,
  40175526789878, 151735331121798, 18008631937170, 71219760253574, 5061661070050, 4994015593186,
  142973597829798, 178749434139152, 160807704070290, 178817080132242, 40177447895778, 242978820794,
  767233251470, 151735603736210, 18188965645360, 8970350289590, 35917914866338, 186952548935334,
  279329809408608, 178851708324388, 152568353432210, 1007812136614, 240305610859170]

theorem prunedTarget64_valid : Valid (maskGraph 7 142938969637522) := by decide +kernel

theorem prunedTarget81_valid : Valid (maskGraph 7 142971685193910) := by decide +kernel

theorem prunedTarget84_valid : Valid (maskGraph 7 143495671220882) := by decide +kernel

theorem prunedTarget93_valid : Valid (maskGraph 7 178156191500340) := by decide +kernel

theorem prunedTarget94_valid : Valid (maskGraph 7 147895093461698) := by decide +kernel

theorem prunedTarget101_valid : Valid (maskGraph 7 178680716738588) := by decide +kernel

theorem prunedTarget102_valid : Valid (maskGraph 7 664688562850) := by decide +kernel

theorem prunedTarget103_valid : Valid (maskGraph 7 26947437472922) := by decide +kernel

theorem prunedTarget105_valid : Valid (maskGraph 7 240269070082690) := by decide +kernel

theorem prunedTarget107_valid : Valid (maskGraph 7 143633110698642) := by decide +kernel

theorem prunedTarget108_valid : Valid (maskGraph 7 40175526789878) := by decide +kernel

theorem prunedTarget109_valid : Valid (maskGraph 7 151735331121798) := by decide +kernel

theorem prunedTarget110_valid : Valid (maskGraph 7 18008631937170) := by decide +kernel

theorem prunedTarget111_valid : Valid (maskGraph 7 71219760253574) := by decide +kernel

theorem prunedTarget112_valid : Valid (maskGraph 7 5061661070050) := by decide +kernel

theorem prunedTarget114_valid : Valid (maskGraph 7 142973597829798) := by decide +kernel

theorem prunedTarget115_valid : Valid (maskGraph 7 178749434139152) := by decide +kernel

theorem prunedTarget117_valid : Valid (maskGraph 7 178817080132242) := by decide +kernel

theorem prunedTarget118_valid : Valid (maskGraph 7 40177447895778) := by decide +kernel

theorem prunedTarget119_valid : Valid (maskGraph 7 242978820794) := by decide +kernel

theorem prunedTarget120_valid : Valid (maskGraph 7 767233251470) := by decide +kernel

theorem prunedTarget121_valid : Valid (maskGraph 7 151735603736210) := by decide +kernel

theorem prunedTarget122_valid : Valid (maskGraph 7 18188965645360) := by decide +kernel

theorem prunedTarget123_valid : Valid (maskGraph 7 8970350289590) := by decide +kernel

theorem prunedTarget124_valid : Valid (maskGraph 7 35917914866338) := by decide +kernel

theorem prunedTarget125_valid : Valid (maskGraph 7 186952548935334) := by decide +kernel

theorem prunedTarget126_valid : Valid (maskGraph 7 279329809408608) := by decide +kernel

theorem prunedTarget127_valid : Valid (maskGraph 7 178851708324388) := by decide +kernel

theorem prunedTarget128_valid : Valid (maskGraph 7 152568353432210) := by decide +kernel

theorem prunedTarget129_valid : Valid (maskGraph 7 1007812136614) := by decide +kernel

theorem prunedTarget130_valid : Valid (maskGraph 7 240305610859170) := by decide +kernel

def prunedContactSwitch0 : SwitchWitness := ⟨64, 16434824, 0, false⟩

theorem prunedContactSwitch0_valid : SwitchRowValid 142938969637522 contactReps131 prunedContactSwitch0 := by
  exact switchRowValidFast_sound 142938969637522 142938969637522 contactReps131 prunedContactSwitch0
    (by decide +kernel) prunedTarget64_valid (by decide +kernel)

def prunedContactSwitch1 : SwitchWitness := ⟨81, 16434824, 0, false⟩

theorem prunedContactSwitch1_valid : SwitchRowValid 142971685193910 contactReps131 prunedContactSwitch1 := by
  exact switchRowValidFast_sound 142971685193910 142971685193910 contactReps131 prunedContactSwitch1
    (by decide +kernel) prunedTarget81_valid (by decide +kernel)

def prunedContactSwitch2 : SwitchWitness := ⟨84, 16434824, 0, false⟩

theorem prunedContactSwitch2_valid : SwitchRowValid 143495671220882 contactReps131 prunedContactSwitch2 := by
  exact switchRowValidFast_sound 143495671220882 143495671220882 contactReps131 prunedContactSwitch2
    (by decide +kernel) prunedTarget84_valid (by decide +kernel)

def prunedContactSwitch3 : SwitchWitness := ⟨93, 16434824, 0, false⟩

theorem prunedContactSwitch3_valid : SwitchRowValid 178156191500340 contactReps131 prunedContactSwitch3 := by
  exact switchRowValidFast_sound 178156191500340 178156191500340 contactReps131 prunedContactSwitch3
    (by decide +kernel) prunedTarget93_valid (by decide +kernel)

def prunedContactSwitch4 : SwitchWitness := ⟨94, 16434824, 0, false⟩

theorem prunedContactSwitch4_valid : SwitchRowValid 147895093461698 contactReps131 prunedContactSwitch4 := by
  exact switchRowValidFast_sound 147895093461698 147895093461698 contactReps131 prunedContactSwitch4
    (by decide +kernel) prunedTarget94_valid (by decide +kernel)

def prunedContactSwitch5 : SwitchWitness := ⟨101, 16434824, 0, false⟩

theorem prunedContactSwitch5_valid : SwitchRowValid 178680716738588 contactReps131 prunedContactSwitch5 := by
  exact switchRowValidFast_sound 178680716738588 178680716738588 contactReps131 prunedContactSwitch5
    (by decide +kernel) prunedTarget101_valid (by decide +kernel)

def prunedContactSwitch6 : SwitchWitness := ⟨102, 16434824, 0, false⟩

theorem prunedContactSwitch6_valid : SwitchRowValid 664688562850 contactReps131 prunedContactSwitch6 := by
  exact switchRowValidFast_sound 664688562850 664688562850 contactReps131 prunedContactSwitch6
    (by decide +kernel) prunedTarget102_valid (by decide +kernel)

def prunedContactSwitch7 : SwitchWitness := ⟨103, 16434824, 0, false⟩

theorem prunedContactSwitch7_valid : SwitchRowValid 26947437472922 contactReps131 prunedContactSwitch7 := by
  exact switchRowValidFast_sound 26947437472922 26947437472922 contactReps131 prunedContactSwitch7
    (by decide +kernel) prunedTarget103_valid (by decide +kernel)

def prunedContactSwitch8 : SwitchWitness := ⟨105, 16434824, 0, false⟩

theorem prunedContactSwitch8_valid : SwitchRowValid 240269070082690 contactReps131 prunedContactSwitch8 := by
  exact switchRowValidFast_sound 240269070082690 240269070082690 contactReps131 prunedContactSwitch8
    (by decide +kernel) prunedTarget105_valid (by decide +kernel)

def prunedContactSwitch9 : SwitchWitness := ⟨107, 16434824, 0, false⟩

theorem prunedContactSwitch9_valid : SwitchRowValid 143633110698642 contactReps131 prunedContactSwitch9 := by
  exact switchRowValidFast_sound 143633110698642 143633110698642 contactReps131 prunedContactSwitch9
    (by decide +kernel) prunedTarget107_valid (by decide +kernel)

def prunedContactSwitch10 : SwitchWitness := ⟨108, 16434824, 0, false⟩

theorem prunedContactSwitch10_valid : SwitchRowValid 40175526789878 contactReps131 prunedContactSwitch10 := by
  exact switchRowValidFast_sound 40175526789878 40175526789878 contactReps131 prunedContactSwitch10
    (by decide +kernel) prunedTarget108_valid (by decide +kernel)

def prunedContactSwitch11 : SwitchWitness := ⟨109, 16434824, 0, false⟩

theorem prunedContactSwitch11_valid : SwitchRowValid 151735331121798 contactReps131 prunedContactSwitch11 := by
  exact switchRowValidFast_sound 151735331121798 151735331121798 contactReps131 prunedContactSwitch11
    (by decide +kernel) prunedTarget109_valid (by decide +kernel)

def prunedContactSwitch12 : SwitchWitness := ⟨110, 16434824, 0, false⟩

theorem prunedContactSwitch12_valid : SwitchRowValid 18008631937170 contactReps131 prunedContactSwitch12 := by
  exact switchRowValidFast_sound 18008631937170 18008631937170 contactReps131 prunedContactSwitch12
    (by decide +kernel) prunedTarget110_valid (by decide +kernel)

def prunedContactSwitch13 : SwitchWitness := ⟨111, 16434824, 0, false⟩

theorem prunedContactSwitch13_valid : SwitchRowValid 71219760253574 contactReps131 prunedContactSwitch13 := by
  exact switchRowValidFast_sound 71219760253574 71219760253574 contactReps131 prunedContactSwitch13
    (by decide +kernel) prunedTarget111_valid (by decide +kernel)

def prunedContactSwitch14 : SwitchWitness := ⟨112, 16434824, 0, false⟩

theorem prunedContactSwitch14_valid : SwitchRowValid 5061661070050 contactReps131 prunedContactSwitch14 := by
  exact switchRowValidFast_sound 5061661070050 5061661070050 contactReps131 prunedContactSwitch14
    (by decide +kernel) prunedTarget112_valid (by decide +kernel)

def prunedContactSwitch15 : SwitchWitness := ⟨114, 16434824, 0, false⟩

theorem prunedContactSwitch15_valid : SwitchRowValid 142973597829798 contactReps131 prunedContactSwitch15 := by
  exact switchRowValidFast_sound 142973597829798 142973597829798 contactReps131 prunedContactSwitch15
    (by decide +kernel) prunedTarget114_valid (by decide +kernel)

def prunedContactSwitch16 : SwitchWitness := ⟨115, 16434824, 0, false⟩

theorem prunedContactSwitch16_valid : SwitchRowValid 178749434139152 contactReps131 prunedContactSwitch16 := by
  exact switchRowValidFast_sound 178749434139152 178749434139152 contactReps131 prunedContactSwitch16
    (by decide +kernel) prunedTarget115_valid (by decide +kernel)

def prunedContactSwitch17 : SwitchWitness := ⟨117, 16434824, 0, false⟩

theorem prunedContactSwitch17_valid : SwitchRowValid 178817080132242 contactReps131 prunedContactSwitch17 := by
  exact switchRowValidFast_sound 178817080132242 178817080132242 contactReps131 prunedContactSwitch17
    (by decide +kernel) prunedTarget117_valid (by decide +kernel)

def prunedContactSwitch18 : SwitchWitness := ⟨118, 16434824, 0, false⟩

theorem prunedContactSwitch18_valid : SwitchRowValid 40177447895778 contactReps131 prunedContactSwitch18 := by
  exact switchRowValidFast_sound 40177447895778 40177447895778 contactReps131 prunedContactSwitch18
    (by decide +kernel) prunedTarget118_valid (by decide +kernel)

def prunedContactSwitch19 : SwitchWitness := ⟨110, 12142529, 38, true⟩

theorem prunedContactSwitch19_valid : SwitchRowValid 595169822268 contactReps131 prunedContactSwitch19 := by
  exact switchRowValidFast_sound 595169822268 18008631937170 contactReps131 prunedContactSwitch19
    (by decide +kernel) prunedTarget110_valid (by decide +kernel)

def prunedContactSwitch20 : SwitchWitness := ⟨105, 6051430, 224, true⟩

theorem prunedContactSwitch20_valid : SwitchRowValid 1007548007090 contactReps131 prunedContactSwitch20 := by
  exact switchRowValidFast_sound 1007548007090 240269070082690 contactReps131 prunedContactSwitch20
    (by decide +kernel) prunedTarget105_valid (by decide +kernel)

def prunedContactSwitch21 : SwitchWitness := ⟨119, 16434824, 0, false⟩

theorem prunedContactSwitch21_valid : SwitchRowValid 242978820794 contactReps131 prunedContactSwitch21 := by
  exact switchRowValidFast_sound 242978820794 242978820794 contactReps131 prunedContactSwitch21
    (by decide +kernel) prunedTarget119_valid (by decide +kernel)

def prunedContactSwitch22 : SwitchWitness := ⟨120, 16434824, 0, false⟩

theorem prunedContactSwitch22_valid : SwitchRowValid 767233251470 contactReps131 prunedContactSwitch22 := by
  exact switchRowValidFast_sound 767233251470 767233251470 contactReps131 prunedContactSwitch22
    (by decide +kernel) prunedTarget120_valid (by decide +kernel)

def prunedContactSwitch23 : SwitchWitness := ⟨111, 9232258, 14, true⟩

theorem prunedContactSwitch23_valid : SwitchRowValid 70423282880178 contactReps131 prunedContactSwitch23 := by
  exact switchRowValidFast_sound 70423282880178 71219760253574 contactReps131 prunedContactSwitch23
    (by decide +kernel) prunedTarget111_valid (by decide +kernel)

def prunedContactSwitch24 : SwitchWitness := ⟨102, 8340290, 70, true⟩

theorem prunedContactSwitch24_valid : SwitchRowValid 143142951769750 contactReps131 prunedContactSwitch24 := by
  exact switchRowValidFast_sound 143142951769750 664688562850 contactReps131 prunedContactSwitch24
    (by decide +kernel) prunedTarget102_valid (by decide +kernel)

def prunedContactSwitch25 : SwitchWitness := ⟨107, 11518850, 38, true⟩

theorem prunedContactSwitch25_valid : SwitchRowValid 17629545926322 contactReps131 prunedContactSwitch25 := by
  exact switchRowValidFast_sound 17629545926322 143633110698642 contactReps131 prunedContactSwitch25
    (by decide +kernel) prunedTarget107_valid (by decide +kernel)

def prunedContactSwitch26 : SwitchWitness := ⟨110, 7008526, 224, false⟩

theorem prunedContactSwitch26_valid : SwitchRowValid 18356706628750 contactReps131 prunedContactSwitch26 := by
  exact switchRowValidFast_sound 18356706628750 18008631937170 contactReps131 prunedContactSwitch26
    (by decide +kernel) prunedTarget110_valid (by decide +kernel)

def prunedContactSwitch27 : SwitchWitness := ⟨121, 16434824, 0, false⟩

theorem prunedContactSwitch27_valid : SwitchRowValid 151735603736210 contactReps131 prunedContactSwitch27 := by
  exact switchRowValidFast_sound 151735603736210 151735603736210 contactReps131 prunedContactSwitch27
    (by decide +kernel) prunedTarget121_valid (by decide +kernel)

def prunedContactSwitch28 : SwitchWitness := ⟨122, 16434824, 0, false⟩

theorem prunedContactSwitch28_valid : SwitchRowValid 18188965645360 contactReps131 prunedContactSwitch28 := by
  exact switchRowValidFast_sound 18188965645360 18188965645360 contactReps131 prunedContactSwitch28
    (by decide +kernel) prunedTarget122_valid (by decide +kernel)

def prunedContactSwitch29 : SwitchWitness := ⟨107, 1709295, 64, false⟩

theorem prunedContactSwitch29_valid : SwitchRowValid 143669920170658 contactReps131 prunedContactSwitch29 := by
  exact switchRowValidFast_sound 143669920170658 143633110698642 contactReps131 prunedContactSwitch29
    (by decide +kernel) prunedTarget107_valid (by decide +kernel)

def prunedContactSwitch30 : SwitchWitness := ⟨123, 16434824, 0, false⟩

theorem prunedContactSwitch30_valid : SwitchRowValid 8970350289590 contactReps131 prunedContactSwitch30 := by
  exact switchRowValidFast_sound 8970350289590 8970350289590 contactReps131 prunedContactSwitch30
    (by decide +kernel) prunedTarget123_valid (by decide +kernel)

def prunedContactSwitch31 : SwitchWitness := ⟨84, 10007613, 46, true⟩

theorem prunedContactSwitch31_valid : SwitchRowValid 9529501590178 contactReps131 prunedContactSwitch31 := by
  exact switchRowValidFast_sound 9529501590178 143495671220882 contactReps131 prunedContactSwitch31
    (by decide +kernel) prunedTarget84_valid (by decide +kernel)

def prunedContactSwitch32 : SwitchWitness := ⟨124, 16434824, 0, false⟩

theorem prunedContactSwitch32_valid : SwitchRowValid 35917914866338 contactReps131 prunedContactSwitch32 := by
  exact switchRowValidFast_sound 35917914866338 35917914866338 contactReps131 prunedContactSwitch32
    (by decide +kernel) prunedTarget124_valid (by decide +kernel)

def prunedContactSwitch33 : SwitchWitness := ⟨125, 16434824, 0, false⟩

theorem prunedContactSwitch33_valid : SwitchRowValid 186952548935334 contactReps131 prunedContactSwitch33 := by
  exact switchRowValidFast_sound 186952548935334 186952548935334 contactReps131 prunedContactSwitch33
    (by decide +kernel) prunedTarget125_valid (by decide +kernel)

def prunedContactSwitch34 : SwitchWitness := ⟨103, 11127865, 182, true⟩

theorem prunedContactSwitch34_valid : SwitchRowValid 71050612609698 contactReps131 prunedContactSwitch34 := by
  exact switchRowValidFast_sound 71050612609698 26947437472922 contactReps131 prunedContactSwitch34
    (by decide +kernel) prunedTarget103_valid (by decide +kernel)

def prunedContactSwitch35 : SwitchWitness := ⟨122, 3084116, 60, true⟩

theorem prunedContactSwitch35_valid : SwitchRowValid 74990144345294 contactReps131 prunedContactSwitch35 := by
  exact switchRowValidFast_sound 74990144345294 18188965645360 contactReps131 prunedContactSwitch35
    (by decide +kernel) prunedTarget122_valid (by decide +kernel)

def prunedContactSwitch36 : SwitchWitness := ⟨112, 13503098, 56, true⟩

theorem prunedContactSwitch36_valid : SwitchRowValid 9039069754034 contactReps131 prunedContactSwitch36 := by
  exact switchRowValidFast_sound 9039069754034 5061661070050 contactReps131 prunedContactSwitch36
    (by decide +kernel) prunedTarget112_valid (by decide +kernel)

def prunedContactSwitch37 : SwitchWitness := ⟨105, 7952455, 4, false⟩

theorem prunedContactSwitch37_valid : SwitchRowValid 4641023234802 contactReps131 prunedContactSwitch37 := by
  exact switchRowValidFast_sound 4641023234802 240269070082690 contactReps131 prunedContactSwitch37
    (by decide +kernel) prunedTarget105_valid (by decide +kernel)

def prunedContactSwitch38 : SwitchWitness := ⟨115, 11289586, 74, false⟩

theorem prunedContactSwitch38_valid : SwitchRowValid 143840979882642 contactReps131 prunedContactSwitch38 := by
  exact switchRowValidFast_sound 143840979882642 178749434139152 contactReps131 prunedContactSwitch38
    (by decide +kernel) prunedTarget115_valid (by decide +kernel)

def prunedContactSwitch39 : SwitchWitness := ⟨114, 10632818, 194, true⟩

theorem prunedContactSwitch39_valid : SwitchRowValid 187509820679846 contactReps131 prunedContactSwitch39 := by
  exact switchRowValidFast_sound 187509820679846 142973597829798 contactReps131 prunedContactSwitch39
    (by decide +kernel) prunedTarget114_valid (by decide +kernel)

def prunedContactSwitch40 : SwitchWitness := ⟨117, 15655010, 84, false⟩

theorem prunedContactSwitch40_valid : SwitchRowValid 5302514782930 contactReps131 prunedContactSwitch40 := by
  exact switchRowValidFast_sound 5302514782930 178817080132242 contactReps131 prunedContactSwitch40
    (by decide +kernel) prunedTarget117_valid (by decide +kernel)

def prunedContactSwitch41 : SwitchWitness := ⟨126, 16434824, 0, false⟩

theorem prunedContactSwitch41_valid : SwitchRowValid 279329809408608 contactReps131 prunedContactSwitch41 := by
  exact switchRowValidFast_sound 279329809408608 279329809408608 contactReps131 prunedContactSwitch41
    (by decide +kernel) prunedTarget126_valid (by decide +kernel)

def prunedContactSwitch42 : SwitchWitness := ⟨81, 4698540, 18, false⟩

theorem prunedContactSwitch42_valid : SwitchRowValid 160668864662150 contactReps131 prunedContactSwitch42 := by
  exact switchRowValidFast_sound 160668864662150 142971685193910 contactReps131 prunedContactSwitch42
    (by decide +kernel) prunedTarget81_valid (by decide +kernel)

def prunedContactSwitch43 : SwitchWitness := ⟨127, 16434824, 0, false⟩

theorem prunedContactSwitch43_valid : SwitchRowValid 178851708324388 contactReps131 prunedContactSwitch43 := by
  exact switchRowValidFast_sound 178851708324388 178851708324388 contactReps131 prunedContactSwitch43
    (by decide +kernel) prunedTarget127_valid (by decide +kernel)

def prunedContactSwitch44 : SwitchWitness := ⟨93, 9412718, 18, false⟩

theorem prunedContactSwitch44_valid : SwitchRowValid 13823662797522 contactReps131 prunedContactSwitch44 := by
  exact switchRowValidFast_sound 13823662797522 178156191500340 contactReps131 prunedContactSwitch44
    (by decide +kernel) prunedTarget93_valid (by decide +kernel)

def prunedContactSwitch45 : SwitchWitness := ⟨107, 4450411, 168, false⟩

theorem prunedContactSwitch45_valid : SwitchRowValid 160600413084306 contactReps131 prunedContactSwitch45 := by
  exact switchRowValidFast_sound 160600413084306 143633110698642 contactReps131 prunedContactSwitch45
    (by decide +kernel) prunedTarget107_valid (by decide +kernel)

def prunedContactSwitch46 : SwitchWitness := ⟨117, 6018817, 38, true⟩

theorem prunedContactSwitch46_valid : SwitchRowValid 178714000409270 contactReps131 prunedContactSwitch46 := by
  exact switchRowValidFast_sound 178714000409270 178817080132242 contactReps131 prunedContactSwitch46
    (by decide +kernel) prunedTarget117_valid (by decide +kernel)

def prunedContactSwitch47 : SwitchWitness := ⟨123, 6052046, 18, false⟩

theorem prunedContactSwitch47_valid : SwitchRowValid 106164755270306 contactReps131 prunedContactSwitch47 := by
  exact switchRowValidFast_sound 106164755270306 8970350289590 contactReps131 prunedContactSwitch47
    (by decide +kernel) prunedTarget123_valid (by decide +kernel)

def prunedContactSwitch48 : SwitchWitness := ⟨125, 6746418, 46, true⟩

theorem prunedContactSwitch48_valid : SwitchRowValid 48973540926178 contactReps131 prunedContactSwitch48 := by
  exact switchRowValidFast_sound 48973540926178 186952548935334 contactReps131 prunedContactSwitch48
    (by decide +kernel) prunedTarget125_valid (by decide +kernel)

def prunedContactSwitch49 : SwitchWitness := ⟨115, 12304537, 52, false⟩

theorem prunedContactSwitch49_valid : SwitchRowValid 75617808845514 contactReps131 prunedContactSwitch49 := by
  exact switchRowValidFast_sound 75617808845514 178749434139152 contactReps131 prunedContactSwitch49
    (by decide +kernel) prunedTarget115_valid (by decide +kernel)

def prunedContactSwitch50 : SwitchWitness := ⟨105, 1891484, 236, true⟩

theorem prunedContactSwitch50_valid : SwitchRowValid 152328573723298 contactReps131 prunedContactSwitch50 := by
  exact switchRowValidFast_sound 152328573723298 240269070082690 contactReps131 prunedContactSwitch50
    (by decide +kernel) prunedTarget105_valid (by decide +kernel)

def prunedContactSwitch51 : SwitchWitness := ⟨128, 16434824, 0, false⟩

theorem prunedContactSwitch51_valid : SwitchRowValid 152568353432210 contactReps131 prunedContactSwitch51 := by
  exact switchRowValidFast_sound 152568353432210 152568353432210 contactReps131 prunedContactSwitch51
    (by decide +kernel) prunedTarget128_valid (by decide +kernel)

def prunedContactSwitch52 : SwitchWitness := ⟨81, 5485102, 38, true⟩

theorem prunedContactSwitch52_valid : SwitchRowValid 517923836602 contactReps131 prunedContactSwitch52 := by
  exact switchRowValidFast_sound 517923836602 142971685193910 contactReps131 prunedContactSwitch52
    (by decide +kernel) prunedTarget81_valid (by decide +kernel)

def prunedContactSwitch53 : SwitchWitness := ⟨64, 14822094, 192, true⟩

theorem prunedContactSwitch53_valid : SwitchRowValid 1076267487922 contactReps131 prunedContactSwitch53 := by
  exact switchRowValidFast_sound 1076267487922 142938969637522 contactReps131 prunedContactSwitch53
    (by decide +kernel) prunedTarget64_valid (by decide +kernel)

def prunedContactSwitch54 : SwitchWitness := ⟨122, 4122818, 98, true⟩

theorem prunedContactSwitch54_valid : SwitchRowValid 664692774566 contactReps131 prunedContactSwitch54 := by
  exact switchRowValidFast_sound 664692774566 18188965645360 contactReps131 prunedContactSwitch54
    (by decide +kernel) prunedTarget122_valid (by decide +kernel)

def prunedContactSwitch55 : SwitchWitness := ⟨129, 16434824, 0, false⟩

theorem prunedContactSwitch55_valid : SwitchRowValid 1007812136614 contactReps131 prunedContactSwitch55 := by
  exact switchRowValidFast_sound 1007812136614 1007812136614 contactReps131 prunedContactSwitch55
    (by decide +kernel) prunedTarget129_valid (by decide +kernel)

def prunedContactSwitch56 : SwitchWitness := ⟨84, 6018817, 38, true⟩

theorem prunedContactSwitch56_valid : SwitchRowValid 143667470453430 contactReps131 prunedContactSwitch56 := by
  exact switchRowValidFast_sound 143667470453430 143495671220882 contactReps131 prunedContactSwitch56
    (by decide +kernel) prunedTarget84_valid (by decide +kernel)

def prunedContactSwitch57 : SwitchWitness := ⟨103, 15647121, 136, true⟩

theorem prunedContactSwitch57_valid : SwitchRowValid 143110770967230 contactReps131 prunedContactSwitch57 := by
  exact switchRowValidFast_sound 143110770967230 26947437472922 contactReps131 prunedContactSwitch57
    (by decide +kernel) prunedTarget103_valid (by decide +kernel)

def prunedContactSwitch58 : SwitchWitness := ⟨84, 1255023, 64, false⟩

theorem prunedContactSwitch58_valid : SwitchRowValid 35779676128828 contactReps131 prunedContactSwitch58 := by
  exact switchRowValidFast_sound 35779676128828 143495671220882 contactReps131 prunedContactSwitch58
    (by decide +kernel) prunedTarget84_valid (by decide +kernel)

def prunedContactSwitch59 : SwitchWitness := ⟨114, 2005234, 192, true⟩

theorem prunedContactSwitch59_valid : SwitchRowValid 143600658734758 contactReps131 prunedContactSwitch59 := by
  exact switchRowValidFast_sound 143600658734758 142973597829798 contactReps131 prunedContactSwitch59
    (by decide +kernel) prunedTarget114_valid (by decide +kernel)

def prunedContactSwitch60 : SwitchWitness := ⟨107, 13702717, 46, true⟩

theorem prunedContactSwitch60_valid : SwitchRowValid 18187356915260 contactReps131 prunedContactSwitch60 := by
  exact switchRowValidFast_sound 18187356915260 143633110698642 contactReps131 prunedContactSwitch60
    (by decide +kernel) prunedTarget107_valid (by decide +kernel)

def prunedContactSwitch61 : SwitchWitness := ⟨117, 1470042, 80, false⟩

theorem prunedContactSwitch61_valid : SwitchRowValid 4915398072436 contactReps131 prunedContactSwitch61 := by
  exact switchRowValidFast_sound 4915398072436 178817080132242 contactReps131 prunedContactSwitch61
    (by decide +kernel) prunedTarget117_valid (by decide +kernel)

def prunedContactSwitch62 : SwitchWitness := ⟨110, 2649885, 30, false⟩

theorem prunedContactSwitch62_valid : SwitchRowValid 70981899437612 contactReps131 prunedContactSwitch62 := by
  exact switchRowValidFast_sound 70981899437612 18008631937170 contactReps131 prunedContactSwitch62
    (by decide +kernel) prunedTarget110_valid (by decide +kernel)

def prunedContactSwitch63 : SwitchWitness := ⟨93, 7619570, 38, true⟩

theorem prunedContactSwitch63_valid : SwitchRowValid 143532207689398 contactReps131 prunedContactSwitch63 := by
  exact switchRowValidFast_sound 143532207689398 178156191500340 contactReps131 prunedContactSwitch63
    (by decide +kernel) prunedTarget93_valid (by decide +kernel)

def prunedContactSwitch64 : SwitchWitness := ⟨109, 14850290, 192, true⟩

theorem prunedContactSwitch64_valid : SwitchRowValid 18256334216870 contactReps131 prunedContactSwitch64 := by
  exact switchRowValidFast_sound 18256334216870 151735331121798 contactReps131 prunedContactSwitch64
    (by decide +kernel) prunedTarget109_valid (by decide +kernel)

def prunedContactSwitch65 : SwitchWitness := ⟨93, 9392663, 32, false⟩

theorem prunedContactSwitch65_valid : SwitchRowValid 143944059617970 contactReps131 prunedContactSwitch65 := by
  exact switchRowValidFast_sound 143944059617970 178156191500340 contactReps131 prunedContactSwitch65
    (by decide +kernel) prunedTarget93_valid (by decide +kernel)

def prunedContactSwitch66 : SwitchWitness := ⟨81, 11731615, 8, false⟩

theorem prunedContactSwitch66_valid : SwitchRowValid 4641025331962 contactReps131 prunedContactSwitch66 := by
  exact switchRowValidFast_sound 4641025331962 142971685193910 contactReps131 prunedContactSwitch66
    (by decide +kernel) prunedTarget81_valid (by decide +kernel)

def prunedContactSwitch67 : SwitchWitness := ⟨108, 13698685, 144, true⟩

theorem prunedContactSwitch67_valid : SwitchRowValid 213326506658458 contactReps131 prunedContactSwitch67 := by
  exact switchRowValidFast_sound 213326506658458 40175526789878 contactReps131 prunedContactSwitch67
    (by decide +kernel) prunedTarget108_valid (by decide +kernel)

def prunedContactSwitch68 : SwitchWitness := ⟨114, 12865195, 20, false⟩

theorem prunedContactSwitch68_valid : SwitchRowValid 70766408405690 contactReps131 prunedContactSwitch68 := by
  exact switchRowValidFast_sound 70766408405690 142973597829798 contactReps131 prunedContactSwitch68
    (by decide +kernel) prunedTarget114_valid (by decide +kernel)

def prunedContactSwitch69 : SwitchWitness := ⟨125, 16122526, 148, true⟩

theorem prunedContactSwitch69_valid : SwitchRowValid 71393472053938 contactReps131 prunedContactSwitch69 := by
  exact switchRowValidFast_sound 71393472053938 186952548935334 contactReps131 prunedContactSwitch69
    (by decide +kernel) prunedTarget125_valid (by decide +kernel)

def prunedContactSwitch70 : SwitchWitness := ⟨84, 14805665, 224, true⟩

theorem prunedContactSwitch70_valid : SwitchRowValid 17972671451834 contactReps131 prunedContactSwitch70 := by
  exact switchRowValidFast_sound 17972671451834 143495671220882 contactReps131 prunedContactSwitch70
    (by decide +kernel) prunedTarget84_valid (by decide +kernel)

def prunedContactSwitch71 : SwitchWitness := ⟨111, 14784882, 48, false⟩

theorem prunedContactSwitch71_valid : SwitchRowValid 5405594518258 contactReps131 prunedContactSwitch71 := by
  exact switchRowValidFast_sound 5405594518258 71219760253574 contactReps131 prunedContactSwitch71
    (by decide +kernel) prunedTarget111_valid (by decide +kernel)

def prunedContactSwitch72 : SwitchWitness := ⟨124, 13759298, 70, true⟩

theorem prunedContactSwitch72_valid : SwitchRowValid 9039071851194 contactReps131 prunedContactSwitch72 := by
  exact switchRowValidFast_sound 9039071851194 35917914866338 contactReps131 prunedContactSwitch72
    (by decide +kernel) prunedTarget124_valid (by decide +kernel)

def prunedContactSwitch73 : SwitchWitness := ⟨102, 13662810, 120, true⟩

theorem prunedContactSwitch73_valid : SwitchRowValid 35427485127354 contactReps131 prunedContactSwitch73 := by
  exact switchRowValidFast_sound 35427485127354 664688562850 contactReps131 prunedContactSwitch73
    (by decide +kernel) prunedTarget102_valid (by decide +kernel)

def prunedContactSwitch74 : SwitchWitness := ⟨122, 8032724, 176, false⟩

theorem prunedContactSwitch74_valid : SwitchRowValid 17835165913786 contactReps131 prunedContactSwitch74 := by
  exact switchRowValidFast_sound 17835165913786 18188965645360 contactReps131 prunedContactSwitch74
    (by decide +kernel) prunedTarget122_valid (by decide +kernel)

def prunedContactSwitch75 : SwitchWitness := ⟨119, 11624697, 84, false⟩

theorem prunedContactSwitch75_valid : SwitchRowValid 9392068421164 contactReps131 prunedContactSwitch75 := by
  exact switchRowValidFast_sound 9392068421164 242978820794 contactReps131 prunedContactSwitch75
    (by decide +kernel) prunedTarget119_valid (by decide +kernel)

def prunedContactSwitch76 : SwitchWitness := ⟨123, 12527116, 138, false⟩

theorem prunedContactSwitch76_valid : SwitchRowValid 71153157298318 contactReps131 prunedContactSwitch76 := by
  exact switchRowValidFast_sound 71153157298318 8970350289590 contactReps131 prunedContactSwitch76
    (by decide +kernel) prunedTarget123_valid (by decide +kernel)

def prunedContactSwitch77 : SwitchWitness := ⟨108, 9264689, 10, false⟩

theorem prunedContactSwitch77_valid : SwitchRowValid 279888155157088 contactReps131 prunedContactSwitch77 := by
  exact switchRowValidFast_sound 279888155157088 40175526789878 contactReps131 prunedContactSwitch77
    (by decide +kernel) prunedTarget108_valid (by decide +kernel)

def prunedContactSwitch78 : SwitchWitness := ⟨109, 1024884, 68, false⟩

theorem prunedContactSwitch78_valid : SwitchRowValid 26562805820070 contactReps131 prunedContactSwitch78 := by
  exact switchRowValidFast_sound 26562805820070 151735331121798 contactReps131 prunedContactSwitch78
    (by decide +kernel) prunedTarget109_valid (by decide +kernel)

def prunedContactSwitch79 : SwitchWitness := ⟨94, 11265793, 134, true⟩

theorem prunedContactSwitch79_valid : SwitchRowValid 22096039303910 contactReps131 prunedContactSwitch79 := by
  exact switchRowValidFast_sound 22096039303910 147895093461698 contactReps131 prunedContactSwitch79
    (by decide +kernel) prunedTarget94_valid (by decide +kernel)

def prunedContactSwitch80 : SwitchWitness := ⟨103, 9970555, 102, true⟩

theorem prunedContactSwitch80_valid : SwitchRowValid 152293681065606 contactReps131 prunedContactSwitch80 := by
  exact switchRowValidFast_sound 152293681065606 26947437472922 contactReps131 prunedContactSwitch80
    (by decide +kernel) prunedTarget103_valid (by decide +kernel)

def prunedContactSwitch81 : SwitchWitness := ⟨114, 3535910, 46, true⟩

theorem prunedContactSwitch81_valid : SwitchRowValid 244703657370208 contactReps131 prunedContactSwitch81 := by
  exact switchRowValidFast_sound 244703657370208 142973597829798 contactReps131 prunedContactSwitch81
    (by decide +kernel) prunedTarget114_valid (by decide +kernel)

def prunedContactSwitch82 : SwitchWitness := ⟨119, 10257835, 42, false⟩

theorem prunedContactSwitch82_valid : SwitchRowValid 147372447680124 contactReps131 prunedContactSwitch82 := by
  exact switchRowValidFast_sound 147372447680124 242978820794 contactReps131 prunedContactSwitch82
    (by decide +kernel) prunedTarget119_valid (by decide +kernel)

def prunedContactSwitch83 : SwitchWitness := ⟨93, 1920205, 208, true⟩

theorem prunedContactSwitch83_valid : SwitchRowValid 40623881869396 contactReps131 prunedContactSwitch83 := by
  exact switchRowValidFast_sound 40623881869396 178156191500340 contactReps131 prunedContactSwitch83
    (by decide +kernel) prunedTarget93_valid (by decide +kernel)

def prunedContactSwitch84 : SwitchWitness := ⟨117, 12293155, 10, false⟩

theorem prunedContactSwitch84_valid : SwitchRowValid 152568892402200 contactReps131 prunedContactSwitch84 := by
  exact switchRowValidFast_sound 152568892402200 178817080132242 contactReps131 prunedContactSwitch84
    (by decide +kernel) prunedTarget117_valid (by decide +kernel)

def prunedContactSwitch85 : SwitchWitness := ⟨109, 5479467, 170, false⟩

theorem prunedContactSwitch85_valid : SwitchRowValid 53750947152530 contactReps131 prunedContactSwitch85 := by
  exact switchRowValidFast_sound 53750947152530 151735331121798 contactReps131 prunedContactSwitch85
    (by decide +kernel) prunedTarget109_valid (by decide +kernel)

def prunedContactSwitch86 : SwitchWitness := ⟨118, 8114337, 20, false⟩

theorem prunedContactSwitch86_valid : SwitchRowValid 152637072913042 contactReps131 prunedContactSwitch86 := by
  exact switchRowValidFast_sound 152637072913042 40177447895778 contactReps131 prunedContactSwitch86
    (by decide +kernel) prunedTarget118_valid (by decide +kernel)

def prunedContactSwitch87 : SwitchWitness := ⟨123, 10302278, 110, true⟩

theorem prunedContactSwitch87_valid : SwitchRowValid 79597128051334 contactReps131 prunedContactSwitch87 := by
  exact switchRowValidFast_sound 79597128051334 8970350289590 contactReps131 prunedContactSwitch87
    (by decide +kernel) prunedTarget123_valid (by decide +kernel)

def prunedContactSwitch88 : SwitchWitness := ⟨120, 15905862, 28, false⟩

theorem prunedContactSwitch88_valid : SwitchRowValid 31029571795552 contactReps131 prunedContactSwitch88 := by
  exact switchRowValidFast_sound 31029571795552 767233251470 contactReps131 prunedContactSwitch88
    (by decide +kernel) prunedTarget120_valid (by decide +kernel)

def prunedContactSwitch89 : SwitchWitness := ⟨81, 14132993, 110, true⟩

theorem prunedContactSwitch89_valid : SwitchRowValid 88642799702690 contactReps131 prunedContactSwitch89 := by
  exact switchRowValidFast_sound 88642799702690 142971685193910 contactReps131 prunedContactSwitch89
    (by decide +kernel) prunedTarget81_valid (by decide +kernel)

def prunedContactSwitch90 : SwitchWitness := ⟨64, 13289031, 36, false⟩

theorem prunedContactSwitch90_valid : SwitchRowValid 75447017019626 contactReps131 prunedContactSwitch90 := by
  exact switchRowValidFast_sound 75447017019626 142938969637522 contactReps131 prunedContactSwitch90
    (by decide +kernel) prunedTarget64_valid (by decide +kernel)

def prunedContactSwitch91 : SwitchWitness := ⟨112, 13940794, 78, true⟩

theorem prunedContactSwitch91_valid : SwitchRowValid 178363994641074 contactReps131 prunedContactSwitch91 := by
  exact switchRowValidFast_sound 178363994641074 5061661070050 contactReps131 prunedContactSwitch91
    (by decide +kernel) prunedTarget112_valid (by decide +kernel)

def prunedContactSwitch92 : SwitchWitness := ⟨125, 15637524, 158, true⟩

theorem prunedContactSwitch92_valid : SwitchRowValid 169920760816290 contactReps131 prunedContactSwitch92 := by
  exact switchRowValidFast_sound 169920760816290 186952548935334 contactReps131 prunedContactSwitch92
    (by decide +kernel) prunedTarget125_valid (by decide +kernel)

def prunedContactSwitch93 : SwitchWitness := ⟨111, 15075186, 72, false⟩

theorem prunedContactSwitch93_valid : SwitchRowValid 57769903424242 contactReps131 prunedContactSwitch93 := by
  exact switchRowValidFast_sound 57769903424242 71219760253574 contactReps131 prunedContactSwitch93
    (by decide +kernel) prunedTarget111_valid (by decide +kernel)

def prunedContactSwitch94 : SwitchWitness := ⟨105, 12533969, 156, true⟩

theorem prunedContactSwitch94_valid : SwitchRowValid 84243678147298 contactReps131 prunedContactSwitch94 := by
  exact switchRowValidFast_sound 84243678147298 240269070082690 contactReps131 prunedContactSwitch94
    (by decide +kernel) prunedTarget105_valid (by decide +kernel)

def prunedContactSwitch95 : SwitchWitness := ⟨114, 15821505, 78, true⟩

theorem prunedContactSwitch95_valid : SwitchRowValid 191910052537058 contactReps131 prunedContactSwitch95 := by
  exact switchRowValidFast_sound 191910052537058 142973597829798 contactReps131 prunedContactSwitch95
    (by decide +kernel) prunedTarget114_valid (by decide +kernel)

def prunedContactSwitch96 : SwitchWitness := ⟨115, 1517817, 80, false⟩

theorem prunedContactSwitch96_valid : SwitchRowValid 222464651211410 contactReps131 prunedContactSwitch96 := by
  exact switchRowValidFast_sound 222464651211410 178749434139152 contactReps131 prunedContactSwitch96
    (by decide +kernel) prunedTarget115_valid (by decide +kernel)

def prunedContactSwitch97 : SwitchWitness := ⟨101, 372652, 80, false⟩

theorem prunedContactSwitch97_valid : SwitchRowValid 92480585635448 contactReps131 prunedContactSwitch97 := by
  exact switchRowValidFast_sound 92480585635448 178680716738588 contactReps131 prunedContactSwitch97
    (by decide +kernel) prunedTarget101_valid (by decide +kernel)

def prunedContactSwitch98 : SwitchWitness := ⟨130, 16434824, 0, false⟩

theorem prunedContactSwitch98_valid : SwitchRowValid 240305610859170 contactReps131 prunedContactSwitch98 := by
  exact switchRowValidFast_sound 240305610859170 240305610859170 contactReps131 prunedContactSwitch98
    (by decide +kernel) prunedTarget130_valid (by decide +kernel)

def prunedContactSwitch99 : SwitchWitness := ⟨93, 16115778, 104, false⟩

theorem prunedContactSwitch99_valid : SwitchRowValid 196409801870872 contactReps131 prunedContactSwitch99 := by
  exact switchRowValidFast_sound 196409801870872 178156191500340 contactReps131 prunedContactSwitch99
    (by decide +kernel) prunedTarget93_valid (by decide +kernel)

def prunedContactSwitch100 : SwitchWitness := ⟨118, 15783110, 198, true⟩

theorem prunedContactSwitch100_valid : SwitchRowValid 123824053064362 contactReps131 prunedContactSwitch100 := by
  exact switchRowValidFast_sound 123824053064362 40177447895778 contactReps131 prunedContactSwitch100
    (by decide +kernel) prunedTarget118_valid (by decide +kernel)

def prunedContactSwitch101 : SwitchWitness := ⟨108, 8039969, 14, true⟩

theorem prunedContactSwitch101_valid : SwitchRowValid 519532599478 contactReps131 prunedContactSwitch101 := by
  exact switchRowValidFast_sound 519532599478 40175526789878 contactReps131 prunedContactSwitch101
    (by decide +kernel) prunedTarget108_valid (by decide +kernel)

def prunedContactSwitch102 : SwitchWitness := ⟨103, 9209214, 22, true⟩

theorem prunedContactSwitch102_valid : SwitchRowValid 4915970347770 contactReps131 prunedContactSwitch102 := by
  exact switchRowValidFast_sound 4915970347770 26947437472922 contactReps131 prunedContactSwitch102
    (by decide +kernel) prunedTarget103_valid (by decide +kernel)

def prunedContactSwitch103 : SwitchWitness := ⟨84, 10030699, 24, true⟩

theorem prunedContactSwitch103_valid : SwitchRowValid 5131461379692 contactReps131 prunedContactSwitch103 := by
  exact switchRowValidFast_sound 5131461379692 143495671220882 contactReps131 prunedContactSwitch103
    (by decide +kernel) prunedTarget84_valid (by decide +kernel)

def prunedContactSwitch104 : SwitchWitness := ⟨114, 1652847, 64, false⟩

theorem prunedContactSwitch104_valid : SwitchRowValid 143454435447482 contactReps131 prunedContactSwitch104 := by
  exact switchRowValidFast_sound 143454435447482 142973597829798 contactReps131 prunedContactSwitch104
    (by decide +kernel) prunedTarget114_valid (by decide +kernel)

def prunedContactSwitch105 : SwitchWitness := ⟨109, 2053772, 196, true⟩

theorem prunedContactSwitch105_valid : SwitchRowValid 9314016867002 contactReps131 prunedContactSwitch105 := by
  exact switchRowValidFast_sound 9314016867002 151735331121798 contactReps131 prunedContactSwitch105
    (by decide +kernel) prunedTarget109_valid (by decide +kernel)

def prunedContactSwitch106 : SwitchWitness := ⟨64, 12764815, 128, false⟩

theorem prunedContactSwitch106_valid : SwitchRowValid 144012779098802 contactReps131 prunedContactSwitch106 := by
  exact switchRowValidFast_sound 144012779098802 142938969637522 contactReps131 prunedContactSwitch106
    (by decide +kernel) prunedTarget64_valid (by decide +kernel)

def prunedContactSwitch107 : SwitchWitness := ⟨109, 9424982, 22, false⟩

theorem prunedContactSwitch107_valid : SwitchRowValid 9460785804966 contactReps131 prunedContactSwitch107 := by
  exact switchRowValidFast_sound 9460785804966 151735331121798 contactReps131 prunedContactSwitch107
    (by decide +kernel) prunedTarget109_valid (by decide +kernel)

def prunedContactSwitch108 : SwitchWitness := ⟨93, 7837718, 36, true⟩

theorem prunedContactSwitch108_valid : SwitchRowValid 9872360518322 contactReps131 prunedContactSwitch108 := by
  exact switchRowValidFast_sound 9872360518322 178156191500340 contactReps131 prunedContactSwitch108
    (by decide +kernel) prunedTarget93_valid (by decide +kernel)

def prunedContactSwitch109 : SwitchWitness := ⟨81, 2018387, 192, true⟩

theorem prunedContactSwitch109_valid : SwitchRowValid 9529507898924 contactReps131 prunedContactSwitch109 := by
  exact switchRowValidFast_sound 9529507898924 142971685193910 contactReps131 prunedContactSwitch109
    (by decide +kernel) prunedTarget81_valid (by decide +kernel)

def prunedContactSwitch110 : SwitchWitness := ⟨108, 16148034, 236, false⟩

theorem prunedContactSwitch110_valid : SwitchRowValid 9803905167014 contactReps131 prunedContactSwitch110 := by
  exact switchRowValidFast_sound 9803905167014 40175526789878 contactReps131 prunedContactSwitch110
    (by decide +kernel) prunedTarget108_valid (by decide +kernel)

def prunedContactSwitch111 : SwitchWitness := ⟨103, 1093547, 140, true⟩

theorem prunedContactSwitch111_valid : SwitchRowValid 143601204385446 contactReps131 prunedContactSwitch111 := by
  exact switchRowValidFast_sound 143601204385446 26947437472922 contactReps131 prunedContactSwitch111
    (by decide +kernel) prunedTarget103_valid (by decide +kernel)

def prunedContactSwitch112 : SwitchWitness := ⟨114, 4683301, 42, false⟩

theorem prunedContactSwitch112_valid : SwitchRowValid 35849199081126 contactReps131 prunedContactSwitch112 := by
  exact switchRowValidFast_sound 35849199081126 142973597829798 contactReps131 prunedContactSwitch112
    (by decide +kernel) prunedTarget114_valid (by decide +kernel)

def prunedContactSwitch113 : SwitchWitness := ⟨119, 13999874, 116, false⟩

theorem prunedContactSwitch113_valid : SwitchRowValid 18599999229606 contactReps131 prunedContactSwitch113 := by
  exact switchRowValidFast_sound 18599999229606 242978820794 contactReps131 prunedContactSwitch113
    (by decide +kernel) prunedTarget119_valid (by decide +kernel)

def prunedContactSwitch114 : SwitchWitness := ⟨81, 12104743, 34, false⟩

theorem prunedContactSwitch114_valid : SwitchRowValid 40177718444798 contactReps131 prunedContactSwitch114 := by
  exact switchRowValidFast_sound 40177718444798 142971685193910 contactReps131 prunedContactSwitch114
    (by decide +kernel) prunedTarget81_valid (by decide +kernel)

def prunedContactSwitch115 : SwitchWitness := ⟨84, 11226817, 36, false⟩

theorem prunedContactSwitch115_valid : SwitchRowValid 179127727344164 contactReps131 prunedContactSwitch115 := by
  exact switchRowValidFast_sound 179127727344164 143495671220882 contactReps131 prunedContactSwitch115
    (by decide +kernel) prunedTarget84_valid (by decide +kernel)

def prunedContactSwitch116 : SwitchWitness := ⟨107, 2805278, 42, false⟩

theorem prunedContactSwitch116_valid : SwitchRowValid 148033875395286 contactReps131 prunedContactSwitch116 := by
  exact switchRowValidFast_sound 148033875395286 143633110698642 contactReps131 prunedContactSwitch116
    (by decide +kernel) prunedTarget107_valid (by decide +kernel)

def prunedContactSwitch117 : SwitchWitness := ⟨117, 13962851, 152, true⟩

theorem prunedContactSwitch117_valid : SwitchRowValid 218282359964374 contactReps131 prunedContactSwitch117 := by
  exact switchRowValidFast_sound 218282359964374 178817080132242 contactReps131 prunedContactSwitch117
    (by decide +kernel) prunedTarget117_valid (by decide +kernel)

def prunedContactSwitch118 : SwitchWitness := ⟨110, 5789665, 62, true⟩

theorem prunedContactSwitch118_valid : SwitchRowValid 88780239180450 contactReps131 prunedContactSwitch118 := by
  exact switchRowValidFast_sound 88780239180450 18008631937170 contactReps131 prunedContactSwitch118
    (by decide +kernel) prunedTarget110_valid (by decide +kernel)

def prunedContactSwitch119 : SwitchWitness := ⟨93, 9196215, 6, false⟩

theorem prunedContactSwitch119_valid : SwitchRowValid 152568894500498 contactReps131 prunedContactSwitch119 := by
  exact switchRowValidFast_sound 152568894500498 178156191500340 contactReps131 prunedContactSwitch119
    (by decide +kernel) prunedTarget93_valid (by decide +kernel)

def prunedContactSwitch120 : SwitchWitness := ⟨94, 15619457, 132, false⟩

theorem prunedContactSwitch120_valid : SwitchRowValid 119772386306144 contactReps131 prunedContactSwitch120 := by
  exact switchRowValidFast_sound 119772386306144 147895093461698 contactReps131 prunedContactSwitch120
    (by decide +kernel) prunedTarget94_valid (by decide +kernel)

def prunedContactSwitch121 : SwitchWitness := ⟨122, 14469826, 96, false⟩

theorem prunedContactSwitch121_valid : SwitchRowValid 279888163643618 contactReps131 prunedContactSwitch121 := by
  exact switchRowValidFast_sound 279888163643618 18188965645360 contactReps131 prunedContactSwitch121
    (by decide +kernel) prunedTarget122_valid (by decide +kernel)

def prunedContactSwitch122 : SwitchWitness := ⟨129, 12461960, 254, true⟩

theorem prunedContactSwitch122_valid : SwitchRowValid 213884852406938 contactReps131 prunedContactSwitch122 := by
  exact switchRowValidFast_sound 213884852406938 1007812136614 contactReps131 prunedContactSwitch122
    (by decide +kernel) prunedTarget129_valid (by decide +kernel)

def prunedContactSwitch123 : SwitchWitness := ⟨114, 16320101, 56, true⟩

theorem prunedContactSwitch123_valid : SwitchRowValid 110563640394486 contactReps131 prunedContactSwitch123 := by
  exact switchRowValidFast_sound 110563640394486 142973597829798 contactReps131 prunedContactSwitch123
    (by decide +kernel) prunedTarget114_valid (by decide +kernel)

def prunedContactSwitch124 : SwitchWitness := ⟨125, 6056281, 40, true⟩

theorem prunedContactSwitch124_valid : SwitchRowValid 217894739428086 contactReps131 prunedContactSwitch124 := by
  exact switchRowValidFast_sound 217894739428086 186952548935334 contactReps131 prunedContactSwitch124
    (by decide +kernel) prunedTarget125_valid (by decide +kernel)

def prunedContactSwitch125 : SwitchWitness := ⟨84, 15896818, 20, false⟩

theorem prunedContactSwitch125_valid : SwitchRowValid 57769905521402 contactReps131 prunedContactSwitch125 := by
  exact switchRowValidFast_sound 57769905521402 143495671220882 contactReps131 prunedContactSwitch125
    (by decide +kernel) prunedTarget84_valid (by decide +kernel)

def prunedContactSwitch126 : SwitchWitness := ⟨111, 11615793, 42, false⟩

theorem prunedContactSwitch126_valid : SwitchRowValid 253910087008994 contactReps131 prunedContactSwitch126 := by
  exact switchRowValidFast_sound 253910087008994 71219760253574 contactReps131 prunedContactSwitch126
    (by decide +kernel) prunedTarget111_valid (by decide +kernel)

def prunedContactSwitch127 : SwitchWitness := ⟨124, 12834059, 106, true⟩

theorem prunedContactSwitch127_valid : SwitchRowValid 75200161778890 contactReps131 prunedContactSwitch127 := by
  exact switchRowValidFast_sound 75200161778890 35917914866338 contactReps131 prunedContactSwitch127
    (by decide +kernel) prunedTarget124_valid (by decide +kernel)

def prunedContactSwitch128 : SwitchWitness := ⟨102, 12443746, 52, false⟩

theorem prunedContactSwitch128_valid : SwitchRowValid 179161818632850 contactReps131 prunedContactSwitch128 := by
  exact switchRowValidFast_sound 179161818632850 664688562850 contactReps131 prunedContactSwitch128
    (by decide +kernel) prunedTarget102_valid (by decide +kernel)

def prunedContactSwitch129 : SwitchWitness := ⟨122, 13463884, 184, true⟩

theorem prunedContactSwitch129_valid : SwitchRowValid 213395226139290 contactReps131 prunedContactSwitch129 := by
  exact switchRowValidFast_sound 213395226139290 18188965645360 contactReps131 prunedContactSwitch129
    (by decide +kernel) prunedTarget122_valid (by decide +kernel)

def prunedContactSwitch130 : SwitchWitness := ⟨119, 14433041, 18, false⟩

theorem prunedContactSwitch130_valid : SwitchRowValid 123371502885510 contactReps131 prunedContactSwitch130 := by
  exact switchRowValidFast_sound 123371502885510 242978820794 contactReps131 prunedContactSwitch130
    (by decide +kernel) prunedTarget119_valid (by decide +kernel)

def prunedContactSwitch131 : SwitchWitness := ⟨93, 9143197, 136, false⟩

theorem prunedContactSwitch131_valid : SwitchRowValid 200423014302450 contactReps131 prunedContactSwitch131 := by
  exact switchRowValidFast_sound 200423014302450 178156191500340 contactReps131 prunedContactSwitch131
    (by decide +kernel) prunedTarget93_valid (by decide +kernel)

def prunedContactSwitch132 : SwitchWitness := ⟨117, 3504158, 14, true⟩

theorem prunedContactSwitch132_valid : SwitchRowValid 257966649553570 contactReps131 prunedContactSwitch132 := by
  exact switchRowValidFast_sound 257966649553570 178817080132242 contactReps131 prunedContactSwitch132
    (by decide +kernel) prunedTarget117_valid (by decide +kernel)

def prunedContactSwitch133 : SwitchWitness := ⟨109, 4066034, 56, true⟩

theorem prunedContactSwitch133_valid : SwitchRowValid 169989480297122 contactReps131 prunedContactSwitch133 := by
  exact switchRowValidFast_sound 169989480297122 151735331121798 contactReps131 prunedContactSwitch133
    (by decide +kernel) prunedTarget109_valid (by decide +kernel)

def prunedContactSwitch134 : SwitchWitness := ⟨118, 13655642, 112, true⟩

theorem prunedContactSwitch134_valid : SwitchRowValid 240374330340002 contactReps131 prunedContactSwitch134 := by
  exact switchRowValidFast_sound 240374330340002 40177447895778 contactReps131 prunedContactSwitch134
    (by decide +kernel) prunedTarget118_valid (by decide +kernel)

def prunedContactSwitch135 : SwitchWitness := ⟨123, 8198918, 108, false⟩

theorem prunedContactSwitch135_valid : SwitchRowValid 236217936679496 contactReps131 prunedContactSwitch135 := by
  exact switchRowValidFast_sound 236217936679496 8970350289590 contactReps131 prunedContactSwitch135
    (by decide +kernel) prunedTarget123_valid (by decide +kernel)

def prunedContactSwitch136 : SwitchWitness := ⟨120, 15656004, 30, true⟩

theorem prunedContactSwitch136_valid : SwitchRowValid 123757780976310 contactReps131 prunedContactSwitch136 := by
  exact switchRowValidFast_sound 123757780976310 767233251470 contactReps131 prunedContactSwitch136
    (by decide +kernel) prunedTarget120_valid (by decide +kernel)

def prunedContactSwitch137 : SwitchWitness := ⟨81, 10304581, 108, false⟩

theorem prunedContactSwitch137_valid : SwitchRowValid 88812213554846 contactReps131 prunedContactSwitch137 := by
  exact switchRowValidFast_sound 88812213554846 142971685193910 contactReps131 prunedContactSwitch137
    (by decide +kernel) prunedTarget81_valid (by decide +kernel)

def prunedContactSwitch138 : SwitchWitness := ⟨64, 16422658, 38, true⟩

theorem prunedContactSwitch138_valid : SwitchRowValid 31029303358194 contactReps131 prunedContactSwitch138 := by
  exact switchRowValidFast_sound 31029303358194 142938969637522 contactReps131 prunedContactSwitch138
    (by decide +kernel) prunedTarget64_valid (by decide +kernel)

def prunedContactSwitch139 : SwitchWitness := ⟨123, 16357922, 142, true⟩

theorem prunedContactSwitch139_valid : SwitchRowValid 106644516803250 contactReps131 prunedContactSwitch139 := by
  exact switchRowValidFast_sound 106644516803250 8970350289590 contactReps131 prunedContactSwitch139
    (by decide +kernel) prunedTarget123_valid (by decide +kernel)

def prunedContactSwitch140 : SwitchWitness := ⟨112, 3373594, 74, false⟩

theorem prunedContactSwitch140_valid : SwitchRowValid 196409810390552 contactReps131 prunedContactSwitch140 := by
  exact switchRowValidFast_sound 196409810390552 5061661070050 contactReps131 prunedContactSwitch140
    (by decide +kernel) prunedTarget112_valid (by decide +kernel)

def prunedContactSwitch141 : SwitchWitness := ⟨125, 15342131, 154, false⟩

theorem prunedContactSwitch141_valid : SwitchRowValid 58147083143374 contactReps131 prunedContactSwitch141 := by
  exact switchRowValidFast_sound 58147083143374 186952548935334 contactReps131 prunedContactSwitch141
    (by decide +kernel) prunedTarget125_valid (by decide +kernel)

def prunedContactSwitch142 : SwitchWitness := ⟨111, 13389397, 196, false⟩

theorem prunedContactSwitch142_valid : SwitchRowValid 205412652855832 contactReps131 prunedContactSwitch142 := by
  exact switchRowValidFast_sound 205412652855832 71219760253574 contactReps131 prunedContactSwitch142
    (by decide +kernel) prunedTarget111_valid (by decide +kernel)

def prunedContactSwitch143 : SwitchWitness := ⟨105, 6879796, 138, false⟩

theorem prunedContactSwitch143_valid : SwitchRowValid 160910791809202 contactReps131 prunedContactSwitch143 := by
  exact switchRowValidFast_sound 160910791809202 240269070082690 contactReps131 prunedContactSwitch143
    (by decide +kernel) prunedTarget105_valid (by decide +kernel)

def prunedContactSwitch144 : SwitchWitness := ⟨114, 3111682, 76, false⟩

theorem prunedContactSwitch144_valid : SwitchRowValid 196411982908952 contactReps131 prunedContactSwitch144 := by
  exact switchRowValidFast_sound 196411982908952 142973597829798 contactReps131 prunedContactSwitch144
    (by decide +kernel) prunedTarget114_valid (by decide +kernel)

def prunedContactSwitch145 : SwitchWitness := ⟨115, 3508694, 152, true⟩

theorem prunedContactSwitch145_valid : SwitchRowValid 205274618673176 contactReps131 prunedContactSwitch145 := by
  exact switchRowValidFast_sound 205274618673176 178749434139152 contactReps131 prunedContactSwitch145
    (by decide +kernel) prunedTarget115_valid (by decide +kernel)

def prunedContactSwitch146 : SwitchWitness := ⟨101, 5999329, 138, false⟩

theorem prunedContactSwitch146_valid : SwitchRowValid 152569429533338 contactReps131 prunedContactSwitch146 := by
  exact switchRowValidFast_sound 152569429533338 178680716738588 contactReps131 prunedContactSwitch146
    (by decide +kernel) prunedTarget101_valid (by decide +kernel)

def prunedContactSwitch147 : SwitchWitness := ⟨130, 3792656, 254, true⟩

theorem prunedContactSwitch147_valid : SwitchRowValid 170161077398162 contactReps131 prunedContactSwitch147 := by
  exact switchRowValidFast_sound 170161077398162 240305610859170 contactReps131 prunedContactSwitch147
    (by decide +kernel) prunedTarget130_valid (by decide +kernel)

def prunedContactSwitch148 : SwitchWitness := ⟨93, 5815236, 106, true⟩

theorem prunedContactSwitch148_valid : SwitchRowValid 66633613063280 contactReps131 prunedContactSwitch148 := by
  exact switchRowValidFast_sound 66633613063280 178156191500340 contactReps131 prunedContactSwitch148
    (by decide +kernel) prunedTarget93_valid (by decide +kernel)

def prunedContactSwitch149 : SwitchWitness := ⟨118, 15637636, 196, false⟩

theorem prunedContactSwitch149_valid : SwitchRowValid 248679559220406 contactReps131 prunedContactSwitch149 := by
  exact switchRowValidFast_sound 248679559220406 40177447895778 contactReps131 prunedContactSwitch149
    (by decide +kernel) prunedTarget118_valid (by decide +kernel)

def prunedContactSwitch150 : SwitchWitness := ⟨126, 15940232, 254, true⟩

theorem prunedContactSwitch150_valid : SwitchRowValid 939906225846 contactReps131 prunedContactSwitch150 := by
  exact switchRowValidFast_sound 939906225846 279329809408608 contactReps131 prunedContactSwitch150
    (by decide +kernel) prunedTarget126_valid (by decide +kernel)

def prunedContactSwitch151 : SwitchWitness := ⟨121, 14034888, 254, true⟩

theorem prunedContactSwitch151_valid : SwitchRowValid 70905456646326 contactReps131 prunedContactSwitch151 := by
  exact switchRowValidFast_sound 70905456646326 151735603736210 contactReps131 prunedContactSwitch151
    (by decide +kernel) prunedTarget121_valid (by decide +kernel)

def prunedContactSwitch152 : SwitchWitness := ⟨122, 3909864, 254, true⟩

theorem prunedContactSwitch152_valid : SwitchRowValid 4917579110646 contactReps131 prunedContactSwitch152 := by
  exact switchRowValidFast_sound 4917579110646 18188965645360 contactReps131 prunedContactSwitch152
    (by decide +kernel) prunedTarget122_valid (by decide +kernel)

def prunedContactSwitch153 : SwitchWitness := ⟨81, 5206369, 26, true⟩

theorem prunedContactSwitch153_valid : SwitchRowValid 35704038906038 contactReps131 prunedContactSwitch153 := by
  exact switchRowValidFast_sound 35704038906038 142971685193910 contactReps131 prunedContactSwitch153
    (by decide +kernel) prunedTarget81_valid (by decide +kernel)

def prunedContactSwitch154 : SwitchWitness := ⟨110, 5370694, 36, false⟩

theorem prunedContactSwitch154_valid : SwitchRowValid 106270286580378 contactReps131 prunedContactSwitch154 := by
  exact switchRowValidFast_sound 106270286580378 18008631937170 contactReps131 prunedContactSwitch154
    (by decide +kernel) prunedTarget110_valid (by decide +kernel)

def prunedContactSwitch155 : SwitchWitness := ⟨111, 474901, 160, true⟩

theorem prunedContactSwitch155_valid : SwitchRowValid 75097346312954 contactReps131 prunedContactSwitch155 := by
  exact switchRowValidFast_sound 75097346312954 71219760253574 contactReps131 prunedContactSwitch155
    (by decide +kernel) prunedTarget111_valid (by decide +kernel)

def prunedContactSwitch156 : SwitchWitness := ⟨102, 15357510, 68, false⟩

theorem prunedContactSwitch156_valid : SwitchRowValid 13301289761530 contactReps131 prunedContactSwitch156 := by
  exact switchRowValidFast_sound 13301289761530 664688562850 contactReps131 prunedContactSwitch156
    (by decide +kernel) prunedTarget102_valid (by decide +kernel)

def prunedContactSwitch157 : SwitchWitness := ⟨107, 3084130, 24, true⟩

theorem prunedContactSwitch157_valid : SwitchRowValid 88083084517050 contactReps131 prunedContactSwitch157 := by
  exact switchRowValidFast_sound 88083084517050 143633110698642 contactReps131 prunedContactSwitch157
    (by decide +kernel) prunedTarget107_valid (by decide +kernel)

def prunedContactSwitch158 : SwitchWitness := ⟨123, 6999664, 254, true⟩

theorem prunedContactSwitch158_valid : SwitchRowValid 88392389791386 contactReps131 prunedContactSwitch158 := by
  exact switchRowValidFast_sound 88392389791386 8970350289590 contactReps131 prunedContactSwitch158
    (by decide +kernel) prunedTarget123_valid (by decide +kernel)

def prunedContactSwitch159 : SwitchWitness := ⟨127, 6147176, 254, true⟩

theorem prunedContactSwitch159_valid : SwitchRowValid 39792782777050 contactReps131 prunedContactSwitch159 := by
  exact switchRowValidFast_sound 39792782777050 178851708324388 contactReps131 prunedContactSwitch159
    (by decide +kernel) prunedTarget127_valid (by decide +kernel)

def prunedContactSwitch160 : SwitchWitness := ⟨105, 5781839, 192, false⟩

theorem prunedContactSwitch160_valid : SwitchRowValid 152808872129202 contactReps131 prunedContactSwitch160 := by
  exact switchRowValidFast_sound 152808872129202 240269070082690 contactReps131 prunedContactSwitch160
    (by decide +kernel) prunedTarget105_valid (by decide +kernel)

def prunedContactSwitch161 : SwitchWitness := ⟨119, 11357304, 254, true⟩

theorem prunedContactSwitch161_valid : SwitchRowValid 213953571887770 contactReps131 prunedContactSwitch161 := by
  exact switchRowValidFast_sound 213953571887770 242978820794 contactReps131 prunedContactSwitch161
    (by decide +kernel) prunedTarget119_valid (by decide +kernel)

def prunedContactSwitch162 : SwitchWitness := ⟨110, 3662036, 232, true⟩

theorem prunedContactSwitch162_valid : SwitchRowValid 245148493165648 contactReps131 prunedContactSwitch162 := by
  exact switchRowValidFast_sound 245148493165648 18008631937170 contactReps131 prunedContactSwitch162
    (by decide +kernel) prunedTarget110_valid (by decide +kernel)

def prunedContactSwitch163 : SwitchWitness := ⟨107, 5749121, 36, false⟩

theorem prunedContactSwitch163_valid : SwitchRowValid 209708935428192 contactReps131 prunedContactSwitch163 := by
  exact switchRowValidFast_sound 209708935428192 143633110698642 contactReps131 prunedContactSwitch163
    (by decide +kernel) prunedTarget107_valid (by decide +kernel)

def prunedContactSwitch164 : SwitchWitness := ⟨124, 4640664, 254, true⟩

theorem prunedContactSwitch164_valid : SwitchRowValid 27326271634090 contactReps131 prunedContactSwitch164 := by
  exact switchRowValidFast_sound 27326271634090 35917914866338 contactReps131 prunedContactSwitch164
    (by decide +kernel) prunedTarget124_valid (by decide +kernel)

def prunedContactSwitch165 : SwitchWitness := ⟨84, 13039635, 42, false⟩

theorem prunedContactSwitch165_valid : SwitchRowValid 80120008587946 contactReps131 prunedContactSwitch165 := by
  exact switchRowValidFast_sound 80120008587946 143495671220882 contactReps131 prunedContactSwitch165
    (by decide +kernel) prunedTarget84_valid (by decide +kernel)

def prunedContactSwitch166 : SwitchWitness := ⟨125, 6646248, 254, true⟩

theorem prunedContactSwitch166_valid : SwitchRowValid 14132131052266 contactReps131 prunedContactSwitch166 := by
  exact switchRowValidFast_sound 14132131052266 186952548935334 contactReps131 prunedContactSwitch166
    (by decide +kernel) prunedTarget125_valid (by decide +kernel)

def prunedContactSwitch167 : SwitchWitness := ⟨103, 3233342, 178, false⟩

theorem prunedContactSwitch167_valid : SwitchRowValid 275559904227880 contactReps131 prunedContactSwitch167 := by
  exact switchRowValidFast_sound 275559904227880 26947437472922 contactReps131 prunedContactSwitch167
    (by decide +kernel) prunedTarget103_valid (by decide +kernel)

def prunedContactSwitch168 : SwitchWitness := ⟨115, 3422706, 106, true⟩

theorem prunedContactSwitch168_valid : SwitchRowValid 137192505778898 contactReps131 prunedContactSwitch168 := by
  exact switchRowValidFast_sound 137192505778898 178749434139152 contactReps131 prunedContactSwitch168
    (by decide +kernel) prunedTarget115_valid (by decide +kernel)

def prunedContactSwitch169 : SwitchWitness := ⟨122, 13389642, 94, false⟩

theorem prunedContactSwitch169_valid : SwitchRowValid 44988411473574 contactReps131 prunedContactSwitch169 := by
  exact switchRowValidFast_sound 44988411473574 18188965645360 contactReps131 prunedContactSwitch169
    (by decide +kernel) prunedTarget122_valid (by decide +kernel)

def prunedContactSwitch170 : SwitchWitness := ⟨114, 8593067, 130, false⟩

theorem prunedContactSwitch170_valid : SwitchRowValid 49316373083256 contactReps131 prunedContactSwitch170 := by
  exact switchRowValidFast_sound 49316373083256 142973597829798 contactReps131 prunedContactSwitch170
    (by decide +kernel) prunedTarget114_valid (by decide +kernel)

def prunedContactSwitch171 : SwitchWitness := ⟨105, 9264199, 6, true⟩

theorem prunedContactSwitch171_valid : SwitchRowValid 275139534796840 contactReps131 prunedContactSwitch171 := by
  exact switchRowValidFast_sound 275139534796840 240269070082690 contactReps131 prunedContactSwitch171
    (by decide +kernel) prunedTarget105_valid (by decide +kernel)

def prunedContactSwitch172 : SwitchWitness := ⟨112, 11600638, 40, false⟩

theorem prunedContactSwitch172_valid : SwitchRowValid 136460652165752 contactReps131 prunedContactSwitch172 := by
  exact switchRowValidFast_sound 136460652165752 5061661070050 contactReps131 prunedContactSwitch172
    (by decide +kernel) prunedTarget112_valid (by decide +kernel)

def prunedContactSwitch173 : SwitchWitness := ⟨107, 9367694, 92, true⟩

theorem prunedContactSwitch173_valid : SwitchRowValid 27259733191338 contactReps131 prunedContactSwitch173 := by
  exact switchRowValidFast_sound 27259733191338 143633110698642 contactReps131 prunedContactSwitch173
    (by decide +kernel) prunedTarget107_valid (by decide +kernel)

def prunedContactSwitch174 : SwitchWitness := ⟨93, 16388253, 26, true⟩

theorem prunedContactSwitch174_valid : SwitchRowValid 119806746064964 contactReps131 prunedContactSwitch174 := by
  exact switchRowValidFast_sound 119806746064964 178156191500340 contactReps131 prunedContactSwitch174
    (by decide +kernel) prunedTarget93_valid (by decide +kernel)

def prunedContactSwitch175 : SwitchWitness := ⟨123, 5512948, 50, true⟩

theorem prunedContactSwitch175_valid : SwitchRowValid 192049107053664 contactReps131 prunedContactSwitch175 := by
  exact switchRowValidFast_sound 192049107053664 8970350289590 contactReps131 prunedContactSwitch175
    (by decide +kernel) prunedTarget123_valid (by decide +kernel)

def prunedContactSwitch176 : SwitchWitness := ⟨117, 7029575, 36, false⟩

theorem prunedContactSwitch176_valid : SwitchRowValid 213772982454954 contactReps131 prunedContactSwitch176 := by
  exact switchRowValidFast_sound 213772982454954 178817080132242 contactReps131 prunedContactSwitch176
    (by decide +kernel) prunedTarget117_valid (by decide +kernel)

def prunedContactSwitch177 : SwitchWitness := ⟨117, 2281118, 232, true⟩

theorem prunedContactSwitch177_valid : SwitchRowValid 119247031120984 contactReps131 prunedContactSwitch177 := by
  exact switchRowValidFast_sound 119247031120984 178817080132242 contactReps131 prunedContactSwitch177
    (by decide +kernel) prunedTarget117_valid (by decide +kernel)

def prunedContactSwitch178 : SwitchWitness := ⟨125, 15339947, 38, false⟩

theorem prunedContactSwitch178_valid : SwitchRowValid 119530431853656 contactReps131 prunedContactSwitch178 := by
  exact switchRowValidFast_sound 119530431853656 186952548935334 contactReps131 prunedContactSwitch178
    (by decide +kernel) prunedTarget125_valid (by decide +kernel)

def prunedContactSwitch179 : SwitchWitness := ⟨115, 5300715, 60, true⟩

theorem prunedContactSwitch179_valid : SwitchRowValid 182626214648440 contactReps131 prunedContactSwitch179 := by
  exact switchRowValidFast_sound 182626214648440 178749434139152 contactReps131 prunedContactSwitch179
    (by decide +kernel) prunedTarget115_valid (by decide +kernel)

def prunedContactSwitch180 : SwitchWitness := ⟨105, 2042061, 108, false⟩

theorem prunedContactSwitch180_valid : SwitchRowValid 227181265859176 contactReps131 prunedContactSwitch180 := by
  exact switchRowValidFast_sound 227181265859176 240269070082690 contactReps131 prunedContactSwitch180
    (by decide +kernel) prunedTarget105_valid (by decide +kernel)

def prunedContactSwitch181 : SwitchWitness := ⟨128, 12954592, 254, true⟩

theorem prunedContactSwitch181_valid : SwitchRowValid 31829306127448 contactReps131 prunedContactSwitch181 := by
  exact switchRowValidFast_sound 31829306127448 152568353432210 contactReps131 prunedContactSwitch181
    (by decide +kernel) prunedTarget128_valid (by decide +kernel)

def prunedContactSwitch182 : SwitchWitness := ⟨120, 16340744, 254, true⟩

theorem prunedContactSwitch182_valid : SwitchRowValid 279888163676898 contactReps131 prunedContactSwitch182 := by
  exact switchRowValidFast_sound 279888163676898 767233251470 contactReps131 prunedContactSwitch182
    (by decide +kernel) prunedTarget120_valid (by decide +kernel)

def prunedContactSwitch183 : SwitchWitness := ⟨108, 14055048, 254, true⟩

theorem prunedContactSwitch183_valid : SwitchRowValid 137397830302784 contactReps131 prunedContactSwitch183 := by
  exact switchRowValidFast_sound 137397830302784 40175526789878 contactReps131 prunedContactSwitch183
    (by decide +kernel) prunedTarget108_valid (by decide +kernel)

def prunedContactSwitch184 : SwitchWitness := ⟨103, 13997536, 254, true⟩

theorem prunedContactSwitch184_valid : SwitchRowValid 80190097649334 contactReps131 prunedContactSwitch184 := by
  exact switchRowValidFast_sound 80190097649334 26947437472922 contactReps131 prunedContactSwitch184
    (by decide +kernel) prunedTarget103_valid (by decide +kernel)

def prunedContactSwitch185 : SwitchWitness := ⟨105, 16340744, 254, true⟩

theorem prunedContactSwitch185_valid : SwitchRowValid 75792051130102 contactReps131 prunedContactSwitch185 := by
  exact switchRowValidFast_sound 75792051130102 240269070082690 contactReps131 prunedContactSwitch185
    (by decide +kernel) prunedTarget105_valid (by decide +kernel)

def prunedContactSwitch186 : SwitchWitness := ⟨109, 15153936, 254, true⟩

theorem prunedContactSwitch186_valid : SwitchRowValid 240372419850942 contactReps131 prunedContactSwitch186 := by
  exact switchRowValidFast_sound 240372419850942 151735331121798 contactReps131 prunedContactSwitch186
    (by decide +kernel) prunedTarget109_valid (by decide +kernel)

def prunedContactSwitch187 : SwitchWitness := ⟨110, 16307480, 254, true⟩

theorem prunedContactSwitch187_valid : SwitchRowValid 270947715944032 contactReps131 prunedContactSwitch187 := by
  exact switchRowValidFast_sound 270947715944032 18008631937170 contactReps131 prunedContactSwitch187
    (by decide +kernel) prunedTarget110_valid (by decide +kernel)

def prunedContactSwitch188 : SwitchWitness := ⟨101, 15947400, 254, true⟩

theorem prunedContactSwitch188_valid : SwitchRowValid 174352636231370 contactReps131 prunedContactSwitch188 := by
  exact switchRowValidFast_sound 174352636231370 178680716738588 contactReps131 prunedContactSwitch188
    (by decide +kernel) prunedTarget101_valid (by decide +kernel)

def prunedContactSwitch189 : SwitchWitness := ⟨102, 4078480, 254, true⟩

theorem prunedContactSwitch189_valid : SwitchRowValid 92823713533694 contactReps131 prunedContactSwitch189 := by
  exact switchRowValidFast_sound 92823713533694 664688562850 contactReps131 prunedContactSwitch189
    (by decide +kernel) prunedTarget102_valid (by decide +kernel)

def prunedContactSwitch190 : SwitchWitness := ⟨107, 15655696, 254, true⟩

theorem prunedContactSwitch190_valid : SwitchRowValid 262740808217298 contactReps131 prunedContactSwitch190 := by
  exact switchRowValidFast_sound 262740808217298 143633110698642 contactReps131 prunedContactSwitch190
    (by decide +kernel) prunedTarget107_valid (by decide +kernel)

def prunedContactSwitch191 : SwitchWitness := ⟨111, 5554080, 254, true⟩

theorem prunedContactSwitch191_valid : SwitchRowValid 84347301068364 contactReps131 prunedContactSwitch191 := by
  exact switchRowValidFast_sound 84347301068364 71219760253574 contactReps131 prunedContactSwitch191
    (by decide +kernel) prunedTarget111_valid (by decide +kernel)

def prunedContactSwitch192 : SwitchWitness := ⟨114, 9926224, 254, true⟩

theorem prunedContactSwitch192_valid : SwitchRowValid 119805376869464 contactReps131 prunedContactSwitch192 := by
  exact switchRowValidFast_sound 119805376869464 142973597829798 contactReps131 prunedContactSwitch192
    (by decide +kernel) prunedTarget114_valid (by decide +kernel)

def prunedContactSwitch193 : SwitchWitness := ⟨112, 15394904, 254, true⟩

theorem prunedContactSwitch193_valid : SwitchRowValid 261945136395376 contactReps131 prunedContactSwitch193 := by
  exact switchRowValidFast_sound 261945136395376 5061661070050 contactReps131 prunedContactSwitch193
    (by decide +kernel) prunedTarget112_valid (by decide +kernel)

def prunedContactSwitch194 : SwitchWitness := ⟨115, 13957272, 254, true⟩

theorem prunedContactSwitch194_valid : SwitchRowValid 101690977989346 contactReps131 prunedContactSwitch194 := by
  exact switchRowValidFast_sound 101690977989346 178749434139152 contactReps131 prunedContactSwitch194
    (by decide +kernel) prunedTarget115_valid (by decide +kernel)

def prunedContactSwitch195 : SwitchWitness := ⟨117, 11219768, 254, true⟩

theorem prunedContactSwitch195_valid : SwitchRowValid 102179802883696 contactReps131 prunedContactSwitch195 := by
  exact switchRowValidFast_sound 102179802883696 178817080132242 contactReps131 prunedContactSwitch195
    (by decide +kernel) prunedTarget117_valid (by decide +kernel)

def prunedContactSwitch196 : SwitchWitness := ⟨118, 7843080, 254, true⟩

theorem prunedContactSwitch196_valid : SwitchRowValid 200845201116386 contactReps131 prunedContactSwitch196 := by
  exact switchRowValidFast_sound 200845201116386 40177447895778 contactReps131 prunedContactSwitch196
    (by decide +kernel) prunedTarget118_valid (by decide +kernel)

def prunedContactSwitch197 : SwitchWitness := ⟨81, 16115848, 254, true⟩

theorem prunedContactSwitch197_valid : SwitchRowValid 209710013627488 contactReps131 prunedContactSwitch197 := by
  exact switchRowValidFast_sound 209710013627488 142971685193910 contactReps131 prunedContactSwitch197
    (by decide +kernel) prunedTarget81_valid (by decide +kernel)

def prunedContactSwitch198 : SwitchWitness := ⟨84, 16083032, 254, true⟩

theorem prunedContactSwitch198_valid : SwitchRowValid 209709745190000 contactReps131 prunedContactSwitch198 := by
  exact switchRowValidFast_sound 209709745190000 143495671220882 contactReps131 prunedContactSwitch198
    (by decide +kernel) prunedTarget84_valid (by decide +kernel)

def prunedContactSwitch199 : SwitchWitness := ⟨93, 13522376, 254, true⟩

theorem prunedContactSwitch199_valid : SwitchRowValid 244490322753136 contactReps131 prunedContactSwitch199 := by
  exact switchRowValidFast_sound 244490322753136 178156191500340 contactReps131 prunedContactSwitch199
    (by decide +kernel) prunedTarget93_valid (by decide +kernel)

def prunedContactSwitch200 : SwitchWitness := ⟨94, 11222792, 254, true⟩

theorem prunedContactSwitch200_valid : SwitchRowValid 227387493508838 contactReps131 prunedContactSwitch200 := by
  exact switchRowValidFast_sound 227387493508838 147895093461698 contactReps131 prunedContactSwitch200
    (by decide +kernel) prunedTarget94_valid (by decide +kernel)

def prunedContactSwitch201 : SwitchWitness := ⟨64, 16394952, 254, true⟩

theorem prunedContactSwitch201_valid : SwitchRowValid 137433024475890 contactReps131 prunedContactSwitch201 := by
  exact switchRowValidFast_sound 137433024475890 142938969637522 contactReps131 prunedContactSwitch201
    (by decide +kernel) prunedTarget64_valid (by decide +kernel)

def prunedContactSwitches : Array SwitchWitness := #[
  prunedContactSwitch0, prunedContactSwitch1, prunedContactSwitch2, prunedContactSwitch3, prunedContactSwitch4, prunedContactSwitch5,
  prunedContactSwitch6, prunedContactSwitch7, prunedContactSwitch8, prunedContactSwitch9, prunedContactSwitch10, prunedContactSwitch11,
  prunedContactSwitch12, prunedContactSwitch13, prunedContactSwitch14, prunedContactSwitch15, prunedContactSwitch16, prunedContactSwitch17,
  prunedContactSwitch18, prunedContactSwitch19, prunedContactSwitch20, prunedContactSwitch21, prunedContactSwitch22, prunedContactSwitch23,
  prunedContactSwitch24, prunedContactSwitch25, prunedContactSwitch26, prunedContactSwitch27, prunedContactSwitch28, prunedContactSwitch29,
  prunedContactSwitch30, prunedContactSwitch31, prunedContactSwitch32, prunedContactSwitch33, prunedContactSwitch34, prunedContactSwitch35,
  prunedContactSwitch36, prunedContactSwitch37, prunedContactSwitch38, prunedContactSwitch39, prunedContactSwitch40, prunedContactSwitch41,
  prunedContactSwitch42, prunedContactSwitch43, prunedContactSwitch44, prunedContactSwitch45, prunedContactSwitch46, prunedContactSwitch47,
  prunedContactSwitch48, prunedContactSwitch49, prunedContactSwitch50, prunedContactSwitch51, prunedContactSwitch52, prunedContactSwitch53,
  prunedContactSwitch54, prunedContactSwitch55, prunedContactSwitch56, prunedContactSwitch57, prunedContactSwitch58, prunedContactSwitch59,
  prunedContactSwitch60, prunedContactSwitch61, prunedContactSwitch62, prunedContactSwitch63, prunedContactSwitch64, prunedContactSwitch65,
  prunedContactSwitch66, prunedContactSwitch67, prunedContactSwitch68, prunedContactSwitch69, prunedContactSwitch70, prunedContactSwitch71,
  prunedContactSwitch72, prunedContactSwitch73, prunedContactSwitch74, prunedContactSwitch75, prunedContactSwitch76, prunedContactSwitch77,
  prunedContactSwitch78, prunedContactSwitch79, prunedContactSwitch80, prunedContactSwitch81, prunedContactSwitch82, prunedContactSwitch83,
  prunedContactSwitch84, prunedContactSwitch85, prunedContactSwitch86, prunedContactSwitch87, prunedContactSwitch88, prunedContactSwitch89,
  prunedContactSwitch90, prunedContactSwitch91, prunedContactSwitch92, prunedContactSwitch93, prunedContactSwitch94, prunedContactSwitch95,
  prunedContactSwitch96, prunedContactSwitch97, prunedContactSwitch98, prunedContactSwitch99, prunedContactSwitch100, prunedContactSwitch101,
  prunedContactSwitch102, prunedContactSwitch103, prunedContactSwitch104, prunedContactSwitch105, prunedContactSwitch106, prunedContactSwitch107,
  prunedContactSwitch108, prunedContactSwitch109, prunedContactSwitch110, prunedContactSwitch111, prunedContactSwitch112, prunedContactSwitch113,
  prunedContactSwitch114, prunedContactSwitch115, prunedContactSwitch116, prunedContactSwitch117, prunedContactSwitch118, prunedContactSwitch119,
  prunedContactSwitch120, prunedContactSwitch121, prunedContactSwitch122, prunedContactSwitch123, prunedContactSwitch124, prunedContactSwitch125,
  prunedContactSwitch126, prunedContactSwitch127, prunedContactSwitch128, prunedContactSwitch129, prunedContactSwitch130, prunedContactSwitch131,
  prunedContactSwitch132, prunedContactSwitch133, prunedContactSwitch134, prunedContactSwitch135, prunedContactSwitch136, prunedContactSwitch137,
  prunedContactSwitch138, prunedContactSwitch139, prunedContactSwitch140, prunedContactSwitch141, prunedContactSwitch142, prunedContactSwitch143,
  prunedContactSwitch144, prunedContactSwitch145, prunedContactSwitch146, prunedContactSwitch147, prunedContactSwitch148, prunedContactSwitch149,
  prunedContactSwitch150, prunedContactSwitch151, prunedContactSwitch152, prunedContactSwitch153, prunedContactSwitch154, prunedContactSwitch155,
  prunedContactSwitch156, prunedContactSwitch157, prunedContactSwitch158, prunedContactSwitch159, prunedContactSwitch160, prunedContactSwitch161,
  prunedContactSwitch162, prunedContactSwitch163, prunedContactSwitch164, prunedContactSwitch165, prunedContactSwitch166, prunedContactSwitch167,
  prunedContactSwitch168, prunedContactSwitch169, prunedContactSwitch170, prunedContactSwitch171, prunedContactSwitch172, prunedContactSwitch173,
  prunedContactSwitch174, prunedContactSwitch175, prunedContactSwitch176, prunedContactSwitch177, prunedContactSwitch178, prunedContactSwitch179,
  prunedContactSwitch180, prunedContactSwitch181, prunedContactSwitch182, prunedContactSwitch183, prunedContactSwitch184, prunedContactSwitch185,
  prunedContactSwitch186, prunedContactSwitch187, prunedContactSwitch188, prunedContactSwitch189, prunedContactSwitch190, prunedContactSwitch191,
  prunedContactSwitch192, prunedContactSwitch193, prunedContactSwitch194, prunedContactSwitch195, prunedContactSwitch196, prunedContactSwitch197,
  prunedContactSwitch198, prunedContactSwitch199, prunedContactSwitch200, prunedContactSwitch201]

theorem prunedContactSwitches_valid : SwitchValid prunedGraphReps7 contactReps131 prunedContactSwitches := by
  intro k
  fin_cases k
  · exact prunedContactSwitch0_valid
  · exact prunedContactSwitch1_valid
  · exact prunedContactSwitch2_valid
  · exact prunedContactSwitch3_valid
  · exact prunedContactSwitch4_valid
  · exact prunedContactSwitch5_valid
  · exact prunedContactSwitch6_valid
  · exact prunedContactSwitch7_valid
  · exact prunedContactSwitch8_valid
  · exact prunedContactSwitch9_valid
  · exact prunedContactSwitch10_valid
  · exact prunedContactSwitch11_valid
  · exact prunedContactSwitch12_valid
  · exact prunedContactSwitch13_valid
  · exact prunedContactSwitch14_valid
  · exact prunedContactSwitch15_valid
  · exact prunedContactSwitch16_valid
  · exact prunedContactSwitch17_valid
  · exact prunedContactSwitch18_valid
  · exact prunedContactSwitch19_valid
  · exact prunedContactSwitch20_valid
  · exact prunedContactSwitch21_valid
  · exact prunedContactSwitch22_valid
  · exact prunedContactSwitch23_valid
  · exact prunedContactSwitch24_valid
  · exact prunedContactSwitch25_valid
  · exact prunedContactSwitch26_valid
  · exact prunedContactSwitch27_valid
  · exact prunedContactSwitch28_valid
  · exact prunedContactSwitch29_valid
  · exact prunedContactSwitch30_valid
  · exact prunedContactSwitch31_valid
  · exact prunedContactSwitch32_valid
  · exact prunedContactSwitch33_valid
  · exact prunedContactSwitch34_valid
  · exact prunedContactSwitch35_valid
  · exact prunedContactSwitch36_valid
  · exact prunedContactSwitch37_valid
  · exact prunedContactSwitch38_valid
  · exact prunedContactSwitch39_valid
  · exact prunedContactSwitch40_valid
  · exact prunedContactSwitch41_valid
  · exact prunedContactSwitch42_valid
  · exact prunedContactSwitch43_valid
  · exact prunedContactSwitch44_valid
  · exact prunedContactSwitch45_valid
  · exact prunedContactSwitch46_valid
  · exact prunedContactSwitch47_valid
  · exact prunedContactSwitch48_valid
  · exact prunedContactSwitch49_valid
  · exact prunedContactSwitch50_valid
  · exact prunedContactSwitch51_valid
  · exact prunedContactSwitch52_valid
  · exact prunedContactSwitch53_valid
  · exact prunedContactSwitch54_valid
  · exact prunedContactSwitch55_valid
  · exact prunedContactSwitch56_valid
  · exact prunedContactSwitch57_valid
  · exact prunedContactSwitch58_valid
  · exact prunedContactSwitch59_valid
  · exact prunedContactSwitch60_valid
  · exact prunedContactSwitch61_valid
  · exact prunedContactSwitch62_valid
  · exact prunedContactSwitch63_valid
  · exact prunedContactSwitch64_valid
  · exact prunedContactSwitch65_valid
  · exact prunedContactSwitch66_valid
  · exact prunedContactSwitch67_valid
  · exact prunedContactSwitch68_valid
  · exact prunedContactSwitch69_valid
  · exact prunedContactSwitch70_valid
  · exact prunedContactSwitch71_valid
  · exact prunedContactSwitch72_valid
  · exact prunedContactSwitch73_valid
  · exact prunedContactSwitch74_valid
  · exact prunedContactSwitch75_valid
  · exact prunedContactSwitch76_valid
  · exact prunedContactSwitch77_valid
  · exact prunedContactSwitch78_valid
  · exact prunedContactSwitch79_valid
  · exact prunedContactSwitch80_valid
  · exact prunedContactSwitch81_valid
  · exact prunedContactSwitch82_valid
  · exact prunedContactSwitch83_valid
  · exact prunedContactSwitch84_valid
  · exact prunedContactSwitch85_valid
  · exact prunedContactSwitch86_valid
  · exact prunedContactSwitch87_valid
  · exact prunedContactSwitch88_valid
  · exact prunedContactSwitch89_valid
  · exact prunedContactSwitch90_valid
  · exact prunedContactSwitch91_valid
  · exact prunedContactSwitch92_valid
  · exact prunedContactSwitch93_valid
  · exact prunedContactSwitch94_valid
  · exact prunedContactSwitch95_valid
  · exact prunedContactSwitch96_valid
  · exact prunedContactSwitch97_valid
  · exact prunedContactSwitch98_valid
  · exact prunedContactSwitch99_valid
  · exact prunedContactSwitch100_valid
  · exact prunedContactSwitch101_valid
  · exact prunedContactSwitch102_valid
  · exact prunedContactSwitch103_valid
  · exact prunedContactSwitch104_valid
  · exact prunedContactSwitch105_valid
  · exact prunedContactSwitch106_valid
  · exact prunedContactSwitch107_valid
  · exact prunedContactSwitch108_valid
  · exact prunedContactSwitch109_valid
  · exact prunedContactSwitch110_valid
  · exact prunedContactSwitch111_valid
  · exact prunedContactSwitch112_valid
  · exact prunedContactSwitch113_valid
  · exact prunedContactSwitch114_valid
  · exact prunedContactSwitch115_valid
  · exact prunedContactSwitch116_valid
  · exact prunedContactSwitch117_valid
  · exact prunedContactSwitch118_valid
  · exact prunedContactSwitch119_valid
  · exact prunedContactSwitch120_valid
  · exact prunedContactSwitch121_valid
  · exact prunedContactSwitch122_valid
  · exact prunedContactSwitch123_valid
  · exact prunedContactSwitch124_valid
  · exact prunedContactSwitch125_valid
  · exact prunedContactSwitch126_valid
  · exact prunedContactSwitch127_valid
  · exact prunedContactSwitch128_valid
  · exact prunedContactSwitch129_valid
  · exact prunedContactSwitch130_valid
  · exact prunedContactSwitch131_valid
  · exact prunedContactSwitch132_valid
  · exact prunedContactSwitch133_valid
  · exact prunedContactSwitch134_valid
  · exact prunedContactSwitch135_valid
  · exact prunedContactSwitch136_valid
  · exact prunedContactSwitch137_valid
  · exact prunedContactSwitch138_valid
  · exact prunedContactSwitch139_valid
  · exact prunedContactSwitch140_valid
  · exact prunedContactSwitch141_valid
  · exact prunedContactSwitch142_valid
  · exact prunedContactSwitch143_valid
  · exact prunedContactSwitch144_valid
  · exact prunedContactSwitch145_valid
  · exact prunedContactSwitch146_valid
  · exact prunedContactSwitch147_valid
  · exact prunedContactSwitch148_valid
  · exact prunedContactSwitch149_valid
  · exact prunedContactSwitch150_valid
  · exact prunedContactSwitch151_valid
  · exact prunedContactSwitch152_valid
  · exact prunedContactSwitch153_valid
  · exact prunedContactSwitch154_valid
  · exact prunedContactSwitch155_valid
  · exact prunedContactSwitch156_valid
  · exact prunedContactSwitch157_valid
  · exact prunedContactSwitch158_valid
  · exact prunedContactSwitch159_valid
  · exact prunedContactSwitch160_valid
  · exact prunedContactSwitch161_valid
  · exact prunedContactSwitch162_valid
  · exact prunedContactSwitch163_valid
  · exact prunedContactSwitch164_valid
  · exact prunedContactSwitch165_valid
  · exact prunedContactSwitch166_valid
  · exact prunedContactSwitch167_valid
  · exact prunedContactSwitch168_valid
  · exact prunedContactSwitch169_valid
  · exact prunedContactSwitch170_valid
  · exact prunedContactSwitch171_valid
  · exact prunedContactSwitch172_valid
  · exact prunedContactSwitch173_valid
  · exact prunedContactSwitch174_valid
  · exact prunedContactSwitch175_valid
  · exact prunedContactSwitch176_valid
  · exact prunedContactSwitch177_valid
  · exact prunedContactSwitch178_valid
  · exact prunedContactSwitch179_valid
  · exact prunedContactSwitch180_valid
  · exact prunedContactSwitch181_valid
  · exact prunedContactSwitch182_valid
  · exact prunedContactSwitch183_valid
  · exact prunedContactSwitch184_valid
  · exact prunedContactSwitch185_valid
  · exact prunedContactSwitch186_valid
  · exact prunedContactSwitch187_valid
  · exact prunedContactSwitch188_valid
  · exact prunedContactSwitch189_valid
  · exact prunedContactSwitch190_valid
  · exact prunedContactSwitch191_valid
  · exact prunedContactSwitch192_valid
  · exact prunedContactSwitch193_valid
  · exact prunedContactSwitch194_valid
  · exact prunedContactSwitch195_valid
  · exact prunedContactSwitch196_valid
  · exact prunedContactSwitch197_valid
  · exact prunedContactSwitch198_valid
  · exact prunedContactSwitch199_valid
  · exact prunedContactSwitch200_valid
  · exact prunedContactSwitch201_valid

theorem contactReps131_size : contactReps131.size = 131 := by decide +kernel

theorem contactReps131_properties : ∀ k : Fin contactReps131.size,
    let E := contactOfGraph (maskGraph 7 contactReps131[k])
    (∀ i, E i i = 0) ∧ (∀ i j, E i j = E j i) ∧
    (∀ i j, i ≠ j → E i j = 1 ∨ E i j = -1) ∧
    (∀ i, i ≠ 0 → E 0 i = 1) := by
  decide +kernel

#print axioms prunedContactSwitches_valid

end LittlewoodCylinders.Upper.GraphCover
