import UpperFiveCertificate
import UpperPolygonData

/-! Generated by research/generate_upper_five_certificates.py.
These 12 records complement the 815 polygon records. Their local
exclusion is proved; completeness of the global enumeration is not. -/

namespace LittlewoodCylinders.Upper

set_option maxRecDepth 100000
set_option maxHeartbeats 0

def fiveRecords : List FiveRecord := [
  { matrixId := 84, orbitId := 112, E := polygonMatrix84,
    χ := orientationFromArray #[1, -1, 1, -1, -1, -1, 1, 1, 1, -1, 1, -1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, 1, -1, 1, 1, -1, 1, -1, -1, 1, 1, 1, -1, -1, 1, 1, -1, 1, 1, -1, 1, -1, -1, 1, -1, 1, -1, -1, 1, 1, 1, 1, 1, -1, 1],
    witness := { labels := ![4, 0, 5, 3, 7], signs := ![-1, -1, -1, -1, -1], globalSign := 1 } },
  { matrixId := 102, orbitId := 1, E := polygonMatrix102,
    χ := orientationFromArray #[1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, -1, 1, -1, -1, 1, -1, -1, -1, -1, 1, 1, 1, 1, -1, 1, -1, -1, 1, 1, -1, 1, 1, 1, 1, -1, -1, -1, 1, -1, 1, -1, -1, 1, -1, 1, -1, 1, 1, 1, 1, -1, -1, -1, -1, -1],
    witness := { labels := ![3, 6, 0, 4, 7], signs := ![-1, -1, -1, -1, -1], globalSign := 1 } },
  { matrixId := 102, orbitId := 10, E := polygonMatrix102,
    χ := orientationFromArray #[1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, 1, 1, -1, 1, -1, 1, 1, -1, 1, -1, -1, 1, -1, 1, 1, -1, 1, -1, -1, 1, -1, -1, 1, -1, 1, -1, 1, 1, -1, 1, -1, -1, 1, -1, 1, -1, 1, 1, -1, 1, -1, 1, -1, 1, -1],
    witness := { labels := ![2, 0, 5, 1, 7], signs := ![1, 1, 1, 1, 1], globalSign := 1 } },
  { matrixId := 103, orbitId := 25, E := polygonMatrix103,
    χ := orientationFromArray #[1, 1, -1, -1, 1, 1, -1, 1, 1, -1, -1, -1, 1, 1, -1, -1, -1, 1, -1, 1, -1, 1, -1, -1, 1, 1, 1, 1, -1, 1, 1, -1, -1, 1, -1, 1, -1, -1, -1, 1, 1, 1, -1, 1, -1, 1, -1, -1, 1, -1, 1, -1, -1, 1, -1, -1],
    witness := { labels := ![0, 5, 7, 2, 4], signs := ![1, 1, 1, -1, 1], globalSign := 1 } },
  { matrixId := 103, orbitId := 26, E := polygonMatrix103,
    χ := orientationFromArray #[1, 1, -1, -1, 1, 1, 1, -1, 1, 1, -1, -1, 1, 1, -1, -1, -1, 1, -1, 1, -1, 1, 1, -1, 1, 1, 1, 1, -1, 1, 1, -1, -1, 1, -1, 1, 1, -1, -1, 1, 1, -1, -1, 1, -1, 1, -1, -1, 1, -1, 1, -1, -1, 1, -1, -1],
    witness := { labels := ![0, 2, 4, 6, 1], signs := ![-1, 1, 1, -1, 1], globalSign := -1 } },
  { matrixId := 103, orbitId := 39, E := polygonMatrix103,
    χ := orientationFromArray #[1, 1, -1, 1, 1, -1, 1, -1, 1, 1, -1, -1, -1, -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, 1, 1, -1, 1, 1, 1, -1, -1, -1, 1, -1, 1, -1, 1, 1, 1, -1, -1, -1, 1, -1, 1, 1, -1, -1, 1, 1, 1, 1, -1, -1, -1, -1],
    witness := { labels := ![2, 7, 5, 0, 4], signs := ![-1, 1, 1, 1, 1], globalSign := 1 } },
  { matrixId := 109, orbitId := 27, E := polygonMatrix109,
    χ := orientationFromArray #[1, -1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, -1, -1, -1, -1, 1, -1, 1, 1, -1, -1, -1, 1, 1, -1, -1, -1, -1, -1, 1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, 1, -1, 1, -1, -1, -1, 1, -1, -1],
    witness := { labels := ![3, 5, 7, 1, 0], signs := ![-1, -1, -1, -1, -1], globalSign := 1 } },
  { matrixId := 110, orbitId := 27, E := polygonMatrix110,
    χ := orientationFromArray #[1, -1, -1, 1, -1, 1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, -1, 1, 1, -1, 1, 1, 1, 1, 1, 1, -1, 1, 1, -1, -1, -1, 1, -1, -1, -1, 1, 1, 1],
    witness := { labels := ![4, 1, 6, 3, 2], signs := ![1, -1, 1, 1, -1], globalSign := -1 } },
  { matrixId := 110, orbitId := 32, E := polygonMatrix110,
    χ := orientationFromArray #[1, -1, -1, 1, -1, -1, -1, 1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, 1, 1, 1, -1, -1, 1, 1, 1, 1, -1, 1, 1, -1, -1, 1, -1, -1, 1, 1, 1, -1, 1, 1, -1, -1, -1, 1, 1, -1, -1, 1, 1, 1, 1, 1, -1],
    witness := { labels := ![2, 0, 6, 1, 7], signs := ![1, 1, 1, 1, 1], globalSign := 1 } },
  { matrixId := 110, orbitId := 79, E := polygonMatrix110,
    χ := orientationFromArray #[1, -1, 1, -1, -1, -1, -1, 1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, 1, -1, 1, 1, 1, -1, 1, -1, -1, -1],
    witness := { labels := ![1, 0, 6, 5, 7], signs := ![1, 1, 1, 1, 1], globalSign := 1 } },
  { matrixId := 117, orbitId := 17, E := polygonMatrix117,
    χ := orientationFromArray #[1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, -1, 1, 1, -1, -1, -1, -1, -1, 1, 1, 1, -1, -1, 1, 1, 1, 1, -1, -1, -1, -1, -1, 1, -1],
    witness := { labels := ![1, 0, 3, 5, 7], signs := ![-1, -1, -1, -1, -1], globalSign := 1 } },
  { matrixId := 122, orbitId := 15, E := polygonMatrix122,
    χ := orientationFromArray #[1, -1, 1, 1, 1, -1, 1, -1, -1, -1, 1, -1, 1, -1, 1, -1, -1, -1, 1, -1, -1, 1, -1, -1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, 1, -1, 1, -1, 1, -1, -1, -1, 1, 1],
    witness := { labels := ![0, 5, 2, 7, 4], signs := ![1, -1, -1, 1, -1], globalSign := -1 } }]

theorem fiveRecords_valid : fiveRecords.all (fun r => decide r.Valid) = true := by
  decide +kernel

theorem fiveRecords_length : fiveRecords.length = 12 := by decide +kernel

theorem recorded_five_excluded (r : FiveRecord) (hr : r ∈ fiveRecords)
    (u m : Fin 8 → Space)
    (hT : ∀ a b, contact u m a b = (r.E a b : ℝ) * ‖cross (u a) (u b)‖)
    (hχ : ∀ a b c, a < b → b < c →
      0 < (r.χ a b c : ℝ) * triple (u a) (u b) (u c)) : False := by
  apply fiveRecord_sound r ?_ u m hT hχ
  exact of_decide_eq_true ((List.all_eq_true.mp fiveRecords_valid) r hr)

theorem recorded_obstruction_count : polygonRecords.length + fiveRecords.length = 827 := by
  rw [polygonRecords_length, fiveRecords_length]

#print axioms fiveRecords_valid
#print axioms recorded_five_excluded

end LittlewoodCylinders.Upper
